app/models/data_set.rb

quick bug fix.

---

app/actors/hyrax/actors/generic_work_actor.rb
app/controllers/hyrax/generic_works_controller.rb
app/forms/deepbluedocs/generic_work_form_behavior.rb
app/forms/hyrax/generic_work_form.rb
app/indexers/generic_work_indexer.rb
app/models/concerns/deepblue/default_metadata.rb
app/models/generic_work.rb
app/presenters/hyrax/generic_work_presenter.rb
app/views/hyrax/generic_works/_generic_work.html.erb
config/initializers/hyrax.rb
config/locales/generic_work.de.yml
config/locales/generic_work.en.yml
config/locales/generic_work.es.yml
config/locales/generic_work.fr.yml
config/locales/generic_work.it.yml
config/locales/generic_work.pt-BR.yml
config/locales/generic_work.zh.yml
spec/actors/hyrax/actors/generic_work_actor_spec.rb
spec/controllers/hyrax/generic_works_controller_spec.rb
spec/features/create_generic_work_spec.rb
spec/forms/hyrax/generic_work_form_spec.rb
spec/models/generic_work_spec.rb
spec/presenters/hyrax/generic_work_presenter_spec.rb

Adds generic work type ( used in deepblue doc )

Add Generic Work Type

---

app/forms/deepbluedocs/dissertation_work_form_behavior.rb
app/models/concerns/deepblue/default_metadata.rb
app/services/hyrax/degree_service.rb
app/services/hyrax/language_service.rb
app/services/hyrax/snre_service.rb
app/views/records/edit_fields/_description_thesisdegreename.html.erb
app/views/records/edit_fields/_language_none.html.erb
app/views/records/edit_fields/_type_snre.html.erb
config/authorities/description_thesisdegreename.yml
config/authorities/language_none.yml
config/authorities/type_snre.yml
config/locales/dissertation.en.yml

to create pick list for dissertations types.

add pick list for dissertation type.

---

.gitignore
config/initializers/hyrax.rb

Make sure to run:
bundle exec rake assets:clobber assets:precompile
in development to get the updated max file size uploaded to change.

BLUEDOC-104 - UI Ingest - Max file size

---

app/forms/deepbluedocs/generic_work_form_behavior.rb

needed to osu ingest script.

---

app/helpers/deepblue/provenance_helper.rb
app/services/deepblue/ingest_fixity_log_reporter.rb
app/services/deepblue/log_exporter.rb
app/services/deepblue/log_filter.rb
app/services/deepblue/log_reader.rb
app/services/deepblue/log_reporter.rb
bin/umrdr_build.sh
bin/umrdr_migrate_dbdv1.sh
bin/umrdr_populate.sh
lib/tasks/new_content_service.rb
spec/helpers/deepblue/provenance_helper_spec.rb

Add support for provenance log reports, including:
* filter for dates
* filter for ids
* filter for class (i.e. Collection, DataSet, FileSet)
* filter for event
* report FileSet ingest fixity results

BLUEDOC-231 - Provenance log report functions

---

app/views/hyrax/uploads/_js_templates.html.erb

this is the second part of the patch.

missing file for multiple files

---

app/forms/deepbluedocs/default_work_form_behavior.rb
app/views/hyrax/base/_attribute_rows.html.erb

and user can only see user notes.

curation notes only entered by admin

---

app/assets/stylesheets/main.scss
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/show.html.erb

- Update work details page to more align with the design system/requested updates

BLUEDOC-307 Update work details page

---

app/views/hyrax/base/_form_member_of_collections.html.erb

note that changing this to be /data/authoritites in the routes file
mount Qa::Engine => '/authorities'
does not fix the issue.  The route still had so be mounted to /authorities.

look up for collection fix due to /data missing.

---

lib/build_content_service.rb

- Missed fixing an "args:" parameter.

BLUEDOC-353 - Update user import task-2

---

app/models/concerns/umrdr/umrdr_work_metadata.rb

Change OtherFundedBy predicate to DISCO.fundedBy
Change OtherLicense predicate to DC.rights
Change curation_notes_admin predicate to ::RDF::Vocab::MODS.note
Change curation_notes_user predicate to ::RDF::Vocab::MODS.note
See https://tools.lib.umich.edu/jira/secure/RapidBoard.jspa?rapidView=32&projectKey=BLUEDOC&view=detail&selectedIssue=BLUEDOC-271 for details

bluedoc-271-work-predicates

---

app/helpers/deepblue_helper.rb
app/views/_ie_announcement.html.erb
app/views/_masthead.html.erb

Add an error message when user has an IE browser

BLUEDOC-349-ie-error

---

lib/diff_content_service.rb
lib/tasks/new_content_service.rb
lib/tasks/populate_dev_app.rake
lib/update_content_service.rb

This includes new migration diff reporting and update modes

BLUEDOC-364 - Update migration scripts

---

app/actors/hyrax/actors/environment.rb
app/actors/hyrax/actors/file_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/uploads_controller.rb
app/helpers/deepblue/ingest_helper.rb
app/helpers/deepblue/json_logger_helper.rb
app/helpers/deepblue/logging_helper.rb
app/helpers/deepblue/upload_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/characterize_job.rb
app/jobs/ingest_job.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/models/job_io_wrapper.rb
config/application.rb
lib/tasks/new_content_service.rb
lib/tasks/upgrade_provenance_log.rake
lib/upload_logger.rb
spec/helpers/deepblue/provenance_helper_spec.rb

Changed ingest jobs to be synchronized under a single add to work job

BLUEDOC-389 - Some files failing to upload in bulk upload 2

---

Gemfile
Gemfile.lock

* Updated gem requirement: bootstrap-sass ~> 3.4.1

BLUEDOC-419 - Update gem dependencie

---

app/models/concerns/umrdr/umrdr_work_metadata.rb

* Updated predicates for curation_notes_admin, curation_notes_user, and rights_license_other

BLUEDOC-422 - Fix metadata predicates

---

app/controllers/hyrax/uploads_controller.rb
spec/models/data_set_spec.rb

* removed references to to_yaml_properties
* removed line from data_set_spec causing problems in ruby 2.5

BLUEDOC-434 - Remove to_yaml_properties

---

app/helpers/deepblue/email_helper.rb
app/jobs/attach_files_to_work_job.rb
config/application.rb
config/locales/hyrax.en.yml

* Added email of list of uploaded files ingested and attached when attach files job is finished

BLUEDOC-432 - Email user and RDS when file uploads are complete

---

app/models/concerns/hydra/access_controls/embargoable.rb

* Embargo (and lease) now correctly set visibility after embargo (or lease)

BLUEDOC-394 - Hyrax 2 embargo workflow has issues

---

app/helpers/deepblue/email_helper.rb

BLUEDOC-432 - Email user and RDS when file uploads are complete 2

---

app/controllers/catalog_controller.rb

this way approved items can show up at the top.

From home page, when user hits GO show last modified items first

---

app/helpers/deepblue/export_files_helper.rb
lib/tasks/yaml_populate_for_work.rake

* Updated file download to try down gem first, then older less efficient copy from uri

BLUEDOC-450 - Export file script error

---

config/initializers/hyrax.rb

* Configuration updates to enable Google Analytics

BLUEDOC-427 - Enable Google Analytics

---

app/models/hyrax/pageview.rb
app/models/hyrax/statistic.rb
app/services/hyrax/analytics.rb
app/services/hyrax/user_stat_importer.rb

* Added debug logging
* Disabled file_set and user stats, leavingn only work stats
* Fixed problem with pageview model not having pageView dimension

BLUEDOC-452 - Update view stats

---

app/actors/hyrax/actors/file_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/file_sets_controller.rb
app/helpers/deepblue/json_logger_helper.rb
app/models/concerns/deepblue/abstract_event_behavior.rb
app/models/concerns/deepblue/file_set_behavior.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/models/file_set.rb
spec/models/concerns/deepblue/abstract_event_behavior_spec.rb
spec/models/file_set_spec.rb

* Provenance log entry when a new version of a file is uploaded
* Provenance log entry when reverting to an older version

BLUEDOC-464 - Provenance log entry for file version changes

---

app/helpers/deepblue_helper.rb
app/views/hyrax/file_sets/_versioning.html.erb
app/views/hyrax/users/_activity_log.html.erb
config/application.rb
config/locales/deepblue.en.yml
config/locales/hyrax.en.yml

* Clean up dates on file version list
* Added option for version dates to be local timezone or UTC
* Clean up dates on activity log and option to be local or UTC

BLUEDOC-465 - Enforce timezone to current for date displays

---

app/helpers/deepblue/json_logger_helper.rb
app/helpers/deepblue/logging_helper.rb
app/helpers/deepblue/provenance_helper.rb
app/helpers/deepblue/upload_helper.rb
config/application.rb
spec/helpers/deepblue/logging_helper_spec.rb
spec/helpers/deepblue/provenance_helper_spec.rb
spec/models/data_set_spec.rb

* Added time_zone attribute to provenance logging
* Added time_zone attribute to logging helper

BLUEDOC-467 - Add timezone to all provenance log writes

---

app/controllers/hyrax/file_sets_controller.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/file_sets/_show_actions.html.erb
app/views/hyrax/file_sets/show.html.erb
config/locales/data_set.en.yml
config/routes.rb

* Added display of provenance log to file set details

BLUEDOC-468 - Provenance log view for file_sets

---

solr/conf/schema.xml
solr/config/schema.xml

* Remove solr deprecated filter: "solr.StandardFilterFactory"
* See: https://github.com/samvera-labs/chimera/pull/38/files

BLUEDOC-463 - Remove deprecated solr filter (from Chimera)

---

app/services/deepblue/doi_minting_service.rb
config/initializers/ezid.rb
config/settings.yml

* Remove all references to EZID use_ssl parameter

BLUEDOC-462 - Remove references to EZID use_ssl parameter

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/sessions_controller.rb
app/models/user.rb
app/views/_user_util_links.html.erb
app/views/sessions/global_logout.html.erb
config/application.rb
config/environments/development.rb
config/environments/test.rb
config/initializers/devise.rb
config/routes.rb
db/migrate/20190206172159_add_columns_to_users.rb
db/schema.rb
lib/devise/behaviors/http_header_authenticatable_behavior.rb
lib/devise/fake_auth_header.rb
lib/devise/models/http_header_authenticatable.rb
lib/devise/strategies/http_header_authenticatable.rb
spec/views/_user_util_links.html.erb_spec.rb

* See: https://github.com/samvera-labs/chimera/pull/37
* Adds config structure to select an authentication method
* Default to UMich authentication
* Add IU's authentication mechanism
* Add comments in files to indicate UMich specific

BLUEDOC-461 - Configurable authentication methods (merge from Chimera)

---

app/views/_masthead_announcement.html.erb
config/application.rb

* Added config flag for masthead / banner

BLUEDOC-433 -- Remove Hyrax 2.0 update banner from production 4/10  ==

---

app/models/concerns/deepblue/email_behavior.rb
app/models/data_set.rb
config/locales/hyrax.en.yml

* Reformat of email includes url, not clickable title

BLUEDOC-441 - Change format of DBD: Work Created notification emails

---

app/jobs/attach_files_to_work_job.rb
config/locales/hyrax.en.yml

BLUEDOC-432 - Email user and RDS when file uploads are complete 3

---

app/views/hyrax/notifications/_notifications.html.erb

* Updated notification create_at dates to be local TZ

BLUEDOC-383 - Fix timestamps to be local timezone

---

app/actors/hyrax/actors/file_set_actor.rb

* Update date_modified when file_set updated via FileSetActor

BLUEDOC-383 - Update date modified when file_set updated

---

app/assets/stylesheets/custom_layout/tweaks.css
config/locales/data_set.en.yml

* Made the provenance log table more compact via CSS
* Changed the verbage on the display provenance log button to include "or Update"

BLUEDOC-489 - Update the provenance log display

---

app/services/hyrax/lock_manager.rb
app/services/hyrax/lockable.rb

BLUEDOC-490 - Investigate Lockable and Redlock

---

app/presenters/hyrax/collection_presenter.rb
app/search_builders/hyrax/collection_member_search_builder.rb
app/search_builders/hyrax/collection_search_builder.rb
app/services/hyrax/collections/collection_member_service.rb
app/services/hyrax/collections/nested_collection_query_service.rb

BLUEDOC-460 - Collections not displaying component works

---

app/assets/stylesheets/custom_layout/tweaks.css
app/controllers/hyrax/collections_controller.rb
app/presenters/hyrax/collection_presenter.rb
app/views/_provenance_log_entries.html.erb
app/views/hyrax/base/show.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/_show_actions.html.erb
app/views/hyrax/dashboard/collections/show.html.erb
config/routes.rb

* Add provenance log for collections to both collection views

BLUEDOC-491 - Add provenance log display to collections ==

---

app/assets/stylesheets/main.scss
app/views/_provenance_log_entries.html.erb
app/views/hyrax/base/_show_actions.html.erb

Group together buttons for Edit and Mint DOI. 
Added panel styling for provenance log.

BLUEDOC-346 Group show actions buttons for clarity

---

app/actors/hyrax/actors/abstract_event_actor.rb
app/actors/hyrax/actors/optimistic_lock_validator.rb
app/controllers/concerns/hyrax/collections_controller_behavior.rb
app/controllers/deepblue/collections_controller_behavior.rb
app/controllers/hyrax/collections_controller.rb
app/controllers/hyrax/dashboard/collections_controller.rb
app/controllers/hyrax/data_sets_controller.rb
app/controllers/hyrax/my/collections_controller.rb

* Added provenance log visibility change for change
* Added provenance log for collection changes from dashboard edit

BLUEDOC-484 - Add collection visibility change to provenance log

---

app/actors/hyrax/actors/optimistic_lock_validator.rb

BLUEDOC-484 - Add collection visibility change to provenance log 2

---

config/initializers/hyrax.rb

* Enabled display of citations for works

BLUEDOC-478 - Add Citation as part of Work display

---

app/assets/stylesheets/custom_layout/tweaks.css
app/views/hyrax/admin/workflows/index.html.erb
app/views/hyrax/dashboard/collections/_default_group.html.erb
app/views/hyrax/dashboard/works/_default_group.html.erb
app/views/hyrax/my/collections/_default_group.html.erb
app/views/hyrax/my/works/_default_group.html.erb
app/views/hyrax/my/works/_list_works.html.erb

add sorting to collection, work, and submission pages and include 

---

app/models/collection.rb
app/models/concerns/umrdr/umrdr_work_metadata.rb
app/models/data_set.rb
app/models/file_set.rb
app/views/hyrax/base/_attribute_rows.html.erb

* fixed admin and user curation notes not saving order
* fixed display of admin and user curation notes to list one note per line

BLUEDOC-498 - Admin curation notes display out of order and no breaks

---

app/views/hyrax/base/_attribute_rows.html.erb

* fixed display for works without curation notes

BLUEDOC-498 - Admin curation notes display out of order and no breaks 2

---

app/models/concerns/umrdr/solr_document_behavior.rb
app/models/concerns/umrdr/umrdr_work_metadata.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb

* added doi_the_correct_one method to solr document behavior so the correct doi value is retreived

BLUEDOC-505 - DOI mint section not displaying correctly for works

---

app/models/concerns/deepblue/file_set_metadata.rb

* changed curation notes order metadata to be single valued

BLUEDOC-507 - File upload fails

---

.gitignore
app/forms/hyrax/forms/collection_form.rb
app/presenters/hyrax/collection_presenter.rb

* added /data to branding assets banner and logo

BLUEDOC-361 - Banner Display - Collection banner doesn't display ==

---

app/actors/hyrax/actors/embargo_actor.rb
app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
app/models/concerns/hydra/access_controls/embargoable.rb
config/application.rb

* After embargo release date, releasing embargo puts embargo in instituion visibility
* Fixed (hopefully) by enforcing a default embargo visibility of open through configurable default after release visibility

BLUEDOC-394 - Hyrax 2 embargo - fix release (version 1)

---

app/views/hyrax/collections/_show_document_list.html.erb
app/views/hyrax/collections/_show_document_list_row.html.erb
app/views/hyrax/dashboard/collections/_show_document_list.html.erb
app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb
app/views/hyrax/my/index.html.erb

BLUEDOC-460 - Collections not displaying component works - 2

---

app/actors/hyrax/actors/attach_members_actor.rb
app/actors/hyrax/actors/before_attach_members_actor.rb
app/views/hyrax/base/_form_member_of_collections.html.erb
app/views/hyrax/base/_form_relationships.html.erb

and remove mapping or work to work functionality.

fix /data issue with mapping coll to work on work edit page

---

app/controllers/hyrax/collections_controller.rb
app/helpers/deepblue/jira_helper.rb
app/jobs/jira_new_ticket_job.rb
app/models/concerns/deepblue/workflow_event_behavior.rb
config/application.rb

* Updated format of ticket (summary and description)
* Added configuration mechanism to turn on and off depending on the hostname
* Added the jira url to the work's curation_notes_admin
* Moved the ticket generation to a job

BLUEDOC-388 - Create ticket in jira when work is created 2

---

public/google75a3ed419e41660c.html

Add static HTML file to enable Google Search Console to enhance Google Analytics

BLUEDOC-368 - Add static file

---

config/application.rb

* Updated config to make localhost automatically be test mode for jira

BLUEDOC-388 - Create ticket in jira when work is created 3

---

app/helpers/hyrax/citations_behaviors/formatters/mla_formatter.rb
config/initializers/hyrax.rb

* Fix work.doi reference
* Enable generate citions

BLUEDOC-560 - Display of generated citations is throwing and error

---

app/assets/stylesheets/main.scss
app/views/catalog/_index_header_list_collection.html.erb

Updates the catalog (browse/search) results.
This also addresses the heading inconsistency from ticket BLUEDOC-523.

BLUEDOC-540 Update catalog styling

---

app/models/concerns/hyrax/collection_behavior.rb

* Failed to include ::Deepblue::WorkflowEventBehavior in CollectionBehavior

BLUEDOC-388 - Create ticket in jira when work is created 4

---

app/assets/stylesheets/main.scss
app/views/hyrax/base/_show_actions.html.erb

Reorganized the buttons/panels per the specifications. The button text will still need to be updated per Rachel's document.

BLUEDOC-534 Add panels around buttons and organize show actions for UX

---

app/models/collection.rb
app/models/data_set.rb
app/models/file_set.rb
app/presenters/hyrax/deepblue_presenter.rb
app/presenters/hyrax/embargo_presenter.rb
app/presenters/hyrax/work_show_presenter.rb
config/locales/deepblue.en.yml

* Change "save data set" to "save work" (deposit and edit buttons)
* Manage embargoes "return to editing this data set" to "... work"
* Manage embargoes type of item for data sets is now work

BLUEDOC-556 - language updates

---

app/actors/hyrax/actors/embargo_actor.rb
app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
app/helpers/hyrax/embargo_helper.rb
app/presenters/hyrax/embargo_presenter.rb
app/services/hydra/embargo_service.rb
app/services/hyrax/embargo_service.rb
lib/tasks/about_to_expire_embargoes_task.rake
lib/tasks/assets_under_embargoe_report_task.rake
lib/tasks/assets_with_deactivated_embargoes.rake
lib/tasks/assets_with_expired_embargoes_report_task.rake
lib/tasks/deactivate_expired_embargoes_task.rake

* shift deactivate embargo duties to helper
* create jobs to report on embargo states
* create job to deactivate embargoes

BLUEDOC-586 - Auto-expire embargoes (step 1)

---

app/controllers/concerns/hyrax/works_controller_behavior.rb
app/controllers/hyrax/file_sets_controller.rb
app/controllers/provenance_log_controller.rb
app/controllers/provenance_log_controller_behavior.rb
app/presenters/provenance_log_presenter.rb
app/search_builders/hyrax/filter_suppressed_with_roles.rb
app/views/_provenance_log_entries2.html.erb
app/views/provenance_log/provenance_log.html.erb
config/routes.rb

* Display provenance log for deleted works and file sets

BLUEDOC-570 - Add access to the provenance log for admin (part 1)

---

app/helpers/job_helper.rb
app/jobs/about_to_expire_embargoes_job.rb
app/jobs/deactivate_expired_embargoes_job.rb
app/jobs/heartbeat_email_job.rb
app/jobs/user_stat_importer_job.rb
app/services/hyrax/user_stat_importer.rb
config/scheduler_jobs_prod.yml

Fixed type in job_options_value method
Updated user stat importer job as well

BLUEDOC-665 - Update scheduler jobs

---

app/controllers/hyrax/static_controller.rb
app/helpers/hyrax/static_content_helper.rb
app/views/hyrax/static/help.html.erb
app/views/hyrax/static/show.html.erb
config/routes.rb

BLUEDOC-671 - Documentation html pages stored in fedora ==

---

Gemfile
Gemfile.lock

BLUEDOC-672 - Update dependencies 4

---

app/helpers/deepblue/email_helper.rb
app/jobs/globus_job.rb
app/mailers/deepblue_mailer.rb
app/models/concerns/deepblue/email_behavior.rb
app/models/concerns/deepblue/workflow_event_behavior.rb
app/models/data_set.rb
config/locales/hyrax.en.yml

This includes renaming email methods for events and support for html emails.

BLUEDOC-628 - Email depositor when work is created

---

app/actors/hyrax/actors/attach_members_actor.rb
app/actors/hyrax/actors/before_add_to_work_actor.rb
app/actors/hyrax/actors/before_attach_members_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/file_sets_controller.rb
app/jobs/attach_files_to_work_job.rb
app/models/concerns/deepblue/provenance_behavior.rb
lib/tasks/new_content_service.rb

Added child add and remove events to works

BLUEDOC-692 - Provenance log not tracking files added/deleted

---

app/views/_logo.html.erb
config/locales/hyrax.en.yml

Made logo configurable from hyrax.en.yml

BLUEDOC-683 - Link MLibrary Logo

---

app/helpers/deepblue/email_helper.rb

Update email sender to convert body and subject to utf-8

BLUEDOC-698 - Record creation did not trigger DBD notification or email

---

app/actors/hyrax/actors/attach_members_actor.rb
app/actors/hyrax/actors/before_add_to_work_actor.rb
app/actors/hyrax/actors/before_attach_members_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/file_sets_controller.rb
app/models/concerns/deepblue/provenance_behavior.rb

Activated debugging statements

BLUEDOC-692 - Provenance log not tracking files added/deleted - 2

---

app/views/hyrax/homepage/_marketing.html.erb
app/views/shared/_footer.html.erb
config/locales/hyrax.en.yml

And moved a few other items to hyrax.en.yml

BLUEDOC-703 - Update copyright statement

---

app/helpers/deepblue/email_helper.rb
app/mailers/deepblue_mailer.rb
app/models/concerns/deepblue/email_behavior.rb

Added cc and bcc to email support

BLUEDOC-336 - Send email to the user after work is approved 3

---

app/assets/stylesheets/main.scss

BLUEDOC-591 - Standardize button display on "Manage embargoes" page

---

app/assets/stylesheets/main.scss
config/locales/hyrax.en.yml

BLUEDOC-591 - Standardize button display on "Manage embargoes" page 2

---

app/controllers/catalog_controller.rb
app/forms/hyrax/forms/file_set_edit_form.rb
app/helpers/deepblue/metadata_helper.rb
app/models/concerns/deepblue/file_set_metadata.rb
app/models/concerns/umrdr/solr_document_behavior.rb
app/models/file_set.rb
app/models/solr_document.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/file_sets/_form.html.erb
app/views/hyrax/file_sets/_show_actions.html.erb
app/views/hyrax/file_sets/_show_details.html.erb
config/locales/file_set.en.yml
config/locales/hyrax.en.yml
spec/models/file_set_spec.rb

This includes additions of the curation_notes_user and _admin.

BLUEDOC-268 - Add description metadata for file sets

---

app/controllers/deepblue/static_content_controller_behavior.rb
app/controllers/work_view_content_controller.rb
app/presenters/work_view_content_presenter.rb
app/views/hyrax/static/work_view_content.html.erb

Changed to use data_send and added image handling.

BLUEDOC-731 - Create work_view_content controller 2

---

app/actors/hyrax/actors/file_actor.rb
app/helpers/deepblue/logging_helper.rb
app/views/hyrax/base/_form_files.html.erb
app/views/hyrax/base/_show_actions.html.erb
config/application.rb
config/initializers/hyrax.rb
config/locales/data_set.en.yml

Updated verbage to reflect larger upload limit.

BLUEDOC-727 - Change file upload limit to 5gb - 2

---

app/assets/javascripts/validations.js
app/views/hyrax/file_sets/_versioning.html.erb
config/locales/deepblue.en.yml
config/locales/file_set.en.yml

As a side effect of this work, the mime type enforcement has been
removed and the upload max file size is being enforced.

BLUEDOC-678 - Disable filename change for versioning

---

app/assets/stylesheets/mlib-styles.css
app/controllers/hyrax/file_sets_controller.rb
app/views/hyrax/file_sets/_versioning.html.erb
app/views/hyrax/uploads/_js_templates_versioning.html.erb
config/locales/hyrax.en.yml

As a side effect of this work, the mime type enforcement has been removed and the upload max file size is being enforced.

BLUEDOC-678 - Disable filename change for versioning 2

---

app/views/hyrax/base/_attribute_rows.html.erb

BLUEDOC-688 - Contact info results in a failed search

---

app/models/concerns/umrdr/umrdr_work_behavior.rb
config/application.rb
config/initializers/globus_service_integration.rb
lib/tasks/new_content_service.rb

Plus a globus bug in umrdr_work_behavior\ and removal of some extra puts

BLUEDOC-797 - Ingest append script publishes works when it shouldn't

---

app/helpers/hyrax/embargo_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/globus_copy_job.rb
app/mailers/deepblue_mailer.rb
app/models/concerns/deepblue/email_behavior.rb
app/views/_contact_us.html.erb
app/views/hyrax/file_sets/_versioning.html.erb
app/views/hyrax/static/_get_help.html.erb
app/views/hyrax/static/agreement.html.erb
app/views/hyrax/static/dbd-documentation-guide.html.erb
app/views/hyrax/static/dbd-glossary.html.erb
app/views/hyrax/static/globus-help.html.erb
app/views/hyrax/static/metadata-guidance.html.erb
config/application.rb
config/environments/test.rb
config/locales/deepblue.en.yml
config/locales/hyrax.en.yml
config/settings.yml

Revising JIRA email connections (deepblue vs. researchdataservices) for DB docs vs. DBD workflows

BLUEDOC-690 - Revising JIRA email connection

---

app/helpers/deepblue/jira_helper.rb
app/jobs/attach_files_to_work_job.rb

BLUEDOC-865 - Add workflow event comments to jira tickets - 2

---

config/initializers/jira_integration.rb

BLUEDOC-865 - Add workflow event comments to jira tickets - 3

---

app/models/user.rb
app/views/hyrax/base/_workflow_actions_widget.html.erb
app/views/hyrax/base/show.html.erb

with this change approvers can approve a work.

allow approver to approve a work

---

app/helpers/deepblue/jira_helper.rb
app/helpers/deepblue/logging_helper.rb

BLUEDOC-872 - Rake task to create test jira ticket - 3

---

app/helpers/deepblue/jira_helper.rb
lib/tasks/submit_test_jira_ticket.rake

BLUEDOC-872 - Rake task to create test jira ticket - 5

---

app/helpers/deepblue/jira_helper.rb
config/initializers/jira_integration.rb

Minor update of terms/veriables from 'reporter' to 'requester'

BLUEDOC-890 - Adding new users as reporter to jira failing - 2

---

app/presenters/hyrax/work_show_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/hyrax/base/_show_work_body.html.erb
app/views/hyrax/collections/_show_descriptions.html.erb
app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
app/views/hyrax/file_sets/_show_details.html.erb
app/views/shared/_show_curation_notes.html.erb
spec/views/hyrax/base/_attributes.html.erb_spec.rb
spec/views/hyrax/file_sets/_actions.html.erb_spec.rb
spec/views/hyrax/shared/_show_curation_note.html.erb_spec.rb
spec/views/hyrax/shared/_show_curation_notes.html.erb_spec.rb
spec/views/hyrax/shared/select_work_type_modal.html.erb_spec.rb

Fix visible curation_note_admin

BLUEDOC-922 - Tombstone works aren't showing metadata-3

---

lib/hydra/derivatives/processors/document.rb
lib/hydra/derivatives/processors/image.rb
lib/hydra/derivatives/processors/processor.rb
lib/hydra/derivatives/processors/shell_based_processor.rb
lib/hydra/derivatives/runners/document_derivatives.rb
lib/hydra/derivatives/runners/image_derivatives.rb
lib/hydra/derivatives/runners/runner.rb
lib/hydra/works/models/concerns/file_set/derivatives.rb

Add new files from external libraries

BLUEDOC-926 - Add timeout for derivative generation-0

---

app/views/hyrax/base/_read_me.html.erb
app/views/hyrax/base/_show_work_body.html.erb
app/views/hyrax/base/_show_work_body_tabbed.html.erb
app/views/hyrax/file_sets/edit.html.erb

BLUEDOC-720 - README tab for works

---

app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/data_sets_controller.rb
app/controllers/hyrax/file_sets_controller.rb
app/helpers/deepblue/file_content_helper.rb
app/helpers/deepblue/metadata_helper.rb
app/models/concerns/deepblue/default_metadata.rb
app/models/concerns/umrdr/solr_document_behavior.rb
app/models/concerns/umrdr/umrdr_work_behavior.rb
app/models/concerns/umrdr/umrdr_work_metadata.rb
app/models/data_set.rb
app/models/solr_document.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/presenters/hyrax/work_show_presenter.rb
app/views/hyrax/base/_read_me.html.erb
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/base/_show_work_body.html.erb
app/views/hyrax/file_sets/_actions.html.erb
config/application.rb
config/locales/data_set.en.yml
config/locales/hyrax.en.yml
config/routes.rb
spec/models/data_set_spec.rb

BLUEDOC-720 - README tab for works - 2

---

app/helpers/deepblue/file_content_helper.rb
app/jobs/ingest_job.rb
app/models/concerns/deepblue/metadata_behavior.rb
app/models/concerns/umrdr/umrdr_work_behavior.rb
app/services/deepblue/ingest_content_service.rb
app/services/hyrax/file_set_derivatives_service.rb
config/application.rb
config/initializers/ingest_service_integration.rb
lib/hydra/derivatives/processors/document.rb
lib/hydra/derivatives/processors/image.rb
lib/hydra/derivatives/processors/shell_based_processor.rb
lib/hydra/derivatives/runners/runner.rb
lib/hydra/works/models/concerns/file_set/derivatives.rb
lib/tasks/new_content_service.rb

Production release v1.0.13 2020/09/24 (finalize config)

BLUEDOC-914 - Deploy to production

---

app/controllers/hyrax/data_sets_controller.rb
app/helpers/deepblue/file_content_helper.rb
app/presenters/hyrax/ds_file_set_presenter.rb
config/application.rb
config/initializers/file_content_integration.rb

Move file content config into initializer.

BLUEDOC-938 - Add markdown support to readme files

---

app/helpers/deepblue/file_content_helper.rb

Added downgrade for html headers

BLUEDOC-938 - Add markdown support to readme files - 2

---

app/actors/hyrax/actors/after_optimistic_lock_validator.rb
app/actors/hyrax/actors/before_model_actor.rb
app/actors/hyrax/actors/data_set_actor.rb
app/actors/hyrax/actors/file_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/catalog_controller.rb
app/controllers/deepblue/collections_controller_behavior.rb
app/controllers/hyrax/dashboard/collections_controller.rb
app/jobs/characterize_job.rb
app/models/collection.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/models/concerns/umrdr/solr_document_behavior.rb
app/models/data_set.rb
app/models/file_set.rb
app/models/job_io_wrapper.rb
app/presenters/hyrax/member_presenter_factory.rb
app/services/deepblue/log_filter.rb
app/services/hyrax/user_stat_importer.rb
app/services/hyrax/workflow/abstract_notification.rb
config/application.rb
config/initializers/file_content_integration.rb
lib/hydra/works/services/add_file_to_file_set.rb

Production release v1.0.14 2020/10/01 (finalize config)

BLUEDOC-953 - Deploy to production

---

app/helpers/deepblue/job_task_helper.rb
app/helpers/job_helper.rb
app/jobs/about_to_expire_embargoes_job.rb
app/jobs/abstract_rake_task_job.rb
app/jobs/characterize_job.rb
app/jobs/deactivate_expired_embargoes_job.rb
app/jobs/heartbeat_email_job.rb
app/jobs/heartbeat_job.rb
app/jobs/ingest_job.rb
app/jobs/rake_task_job.rb
app/jobs/user_stat_importer_job.rb
app/jobs/works_report_job.rb
config/application.rb
config/initializers/job_task_integration.rb
lib/tasks/run_job_task.rake

* Created generic rake task to invoke jobs
* Created generic job to run rake tasks
* This is only potentially circular

BLUEDOC-923 - Create a mechanism to cleanup shared/tmp directory

---

app/helpers/deepblue/file_content_helper.rb
config/initializers/file_content_integration.rb

* Proxy error due to too many file sets scanned for readme

BLUEDOC-966 - Proxy error on view work

---

app/presenters/hyrax/deepblue_presenter.rb
app/presenters/hyrax/work_show_presenter.rb
app/views/hyrax/base/_show_actions.html.erb
spec/factories/data_sets.rb
spec/presenters/hyrax/data_set_presenter_spec.rb
spec/presenters/hyrax/work_show_presenter_spec.rb
spec/views/hyrax/base/_show_actions.html.erb_spec.rb

* This includes added tests for globus button permissions and appearance

BLUEDOC-967 - Globus buttons missing from works

---

app/helpers/deepblue/job_task_helper.rb
app/jobs/abstract_rake_task_job.rb
app/jobs/find_and_fix_empty_file_sizes_behavior.rb
app/jobs/find_and_fix_job.rb
app/models/concerns/deepblue/total_file_size_work_behavior.rb
app/models/concerns/umrdr/umrdr_work_behavior.rb
config/initializers/job_task_integration.rb
config/scheduler_jobs_prod.yml
lib/tasks/run_job_task.rake

* includes generic find and fix job

BLUEDOC-969 - Add job to find and fix zero file set sizes

---

app/jobs/about_to_expire_embargoes_job.rb
app/jobs/deactivate_expired_embargoes_job.rb
app/jobs/find_and_fix_job.rb
app/jobs/heartbeat_email_job.rb
app/jobs/inherit_permissions_job.rb
app/jobs/rake_task_job.rb
app/jobs/user_stat_importer_job.rb
app/jobs/works_report_job.rb
config/scheduler_jobs_prod.yml

Update schedule to include find and fix job

BLUEDOC-952 - Add find and fix job to fix nils in ordered members - 2

---

db/migrate/20201020181055_create_ahoy_visits_and_events.rb
db/migrate/20201021145350_add_cc_id_to_ahoy_events.rb
db/schema.rb

Hopefully, this will fix the deployment error from adding an index to
ahoy events.

BLUEDOC-963 - Data Capture - Create Logs - 4

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/custom_layout/tweaks.css
app/controllers/concerns/hyrax/admin/stats_behavior.rb
app/helpers/analytics_helper.rb
app/presenters/hyrax/admin_stats_presenter.rb
app/presenters/hyrax/collection_presenter.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/hyrax/admin/stats/_stats_by_date.html.erb
app/views/hyrax/admin/stats/show.html.erb
app/views/hyrax/file_sets/_file_set_description.html.erb
app/views/hyrax/file_sets/show.html.erb
app/views/shared/_page_hits.html.erb
app/views/shared/_page_hits_cc.html.erb
app/views/shared/_page_hits_header_cc.html.erb

BLUEDOC-963 - Data Capture - Create Logs - 5

---

app/actors/hyrax/actors/attach_members_actor.rb
app/actors/hyrax/actors/before_add_to_work_actor.rb
app/controllers/concerns/hyrax/collections_controller_behavior.rb
app/controllers/hyrax/collections_controller.rb
app/controllers/hyrax/file_sets_controller.rb
app/controllers/hyrax/my/collections_controller.rb
app/helpers/analytics_helper.rb
app/helpers/hyrax/embargo_helper.rb
app/helpers/persist_helper.rb
app/jobs/doi_minting_job.rb
app/services/deepblue/analytics_integration_service.rb
config/initializers/analytics_integration.rb
lib/ahoy/tracker.rb

Added date range filter to hit graphs

BLUEDOC-963 - Data Capture - Create Logs - 7

---

app/models/collection.rb

Copying the way resource_type is set for Dataset.

set resource_type to Collection when a collection is created

---

app/controllers/hyrax/permissions_controller.rb
app/helpers/hyrax/ability_helper.rb
app/helpers/hyrax/user_helper.rb
app/models/ability.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/models/concerns/hydra/access_controls/permissions.rb
app/models/concerns/hydra/role_management/user_roles.rb
app/models/concerns/hyrax/ability.rb
app/models/job_io_wrapper.rb
app/models/user.rb
config/application.rb
config/role_map.yml
lib/blacklight/access_controls/ability.rb
lib/blacklight/access_controls/enforcement.rb
lib/blacklight/access_controls/permissions_query.rb
lib/hydra/ability.rb
spec/controllers/concerns/deepblue/zip_download_controller_behavior_spec.rb

Don't merge this until after the production push Thursday, 08/19

BLUEDOC-1219 - Enable user groups (merge after prod push)

---

app/helpers/analytics_helper.rb
app/jobs/update_condensed_events_job.rb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_default_group.html.erb
app/views/hyrax/my/works/_list_works.html.erb
spec/jobs/update_condensed_events_job_spec.rb

Before enabling the job that runs the status do this from the rails console:
> Ahoy::CondensedEvent.all
> ::AnalyticsHelper.drop_condesed_event_downloads
>  Ahoy::CondensedEvent.all
> ::AnalyticsHelper.initialize_condensed_event_downloads
> Ahoy::CondensedEvent.all

include globus and zip in stats

---

app/controllers/admin_only_controller_behavior.rb
app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/controllers/email_dashboard_controller.rb
app/controllers/email_subscriptions_controller.rb
app/controllers/ingest_dashboard_controller.rb
app/controllers/job_statuses_controller.rb
app/controllers/job_workers_controller.rb
app/controllers/report_dashboard_controller.rb
app/controllers/scheduler_dashboard_controller.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1269

BLUEDOC-1268 - Update manage scheduler interface 2

---

app/controllers/concerns/hyrax/contact_form_controller.rb
app/models/concerns/hyrax/file_set/characterization.rb
app/services/deepblue/ingest_integration_service.rb
app/services/hyrax/contact_form_integration_service.rb
app/views/hyrax/contact_form/new.html.erb
config/initializers/contact_form_service_integration.rb
config/initializers/ingest_service_integration.rb
config/settings.yml
lib/active_fedora/persistence.rb
lib/hydra/works/services/characterization_service.rb
spec/controllers/hyrax/contact_form_controller_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1264

BLUEDOC-1264 - Add akismet contact form spam filtering

---

app/controllers/concerns/hyrax/contact_form_controller.rb
app/helpers/deepblue/file_content_helper.rb
app/helpers/deepblue/job_task_helper.rb
app/helpers/persist_helper.rb
app/jobs/deepblue/deepblue_job.rb
app/jobs/user_stat_importer_job.rb
app/jobs/works_report_job.rb
app/views/hyrax/contact_form/new.html.erb
config/initializers/contact_form_service_integration.rb
spec/helpers/deepblue/job_task_helper_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1264

BLUEDOC-1264 - Add akismet contact form spam filtering 2

---

app/helpers/deepblue/job_task_helper.rb
app/jobs/sitemap_generator_job.rb
spec/helpers/deepblue/job_task_helper_spec.rb
spec/jobs/about_to_expire_embargoes_job_spec.rb
spec/jobs/clean_derivatives_dir_job_spec.rb
spec/jobs/deepblue/deepblue_job_spec.rb
spec/jobs/heartbeat_email_job_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1275

BLUEDOC-1275 - Fix sitemap summary job running from scheduler

---

app/jobs/fedora_accessible_job.rb
app/jobs/find_and_fix_job.rb
app/jobs/find_and_fix_old_job.rb
app/jobs/multiple_ingest_scripts_job.rb
app/jobs/rake_task_job.rb
app/jobs/sitemap_generator_job.rb
spec/jobs/about_to_expire_embargoes_job_spec.rb
spec/jobs/clean_derivatives_dir_job_spec.rb
spec/jobs/deactivate_expired_embargoes_job_spec.rb
spec/jobs/deepblue/deepblue_job_spec.rb
spec/jobs/find_and_fix_job_spec.rb
spec/jobs/find_and_fix_old_job_spec.rb
spec/jobs/globus_errors_report_job_spec.rb
spec/jobs/globus_status_report_job_spec.rb
spec/jobs/heartbeat_email_job_spec.rb
spec/jobs/multiple_ingest_scripts_job_spec.rb
spec/jobs/rake_task_job_spec.rb
spec/jobs/sitemap_generator_job_spec.rb
spec/jobs/update_condensed_events_job_spec.rb

Jira ticket: https://tools.lib.umich.edu/jira/browse/BLUEDOC-1275

BLUEDOC-1275 - Fix sitemap summary job running from scheduler - 2

---

app/controllers/hyrax/dashboard/collections_controller.rb
spec/controllers/hyrax/dashboard/collections_controller_spec.rb

user sent to collection page, rather than stay in edit collection page

---

Gemfile
Gemfile.lock
lib/active_triples/util/extended_bounded_description.rb
spec/lib/active_fedora/persistence_spec.rb
spec/lib/active_triples/util/extended_bounded_description_spec.rb
spec/lib/browse_everything/driver/authentication_factory.rb
spec/lib/browse_everything/driver/base.rb
spec/lib/browse_everything/driver/box.rb
spec/lib/browse_everything/driver/dropbox.rb
spec/lib/browse_everything/driver/file_system.rb
spec/lib/browse_everything/driver/google_drive.rb
spec/lib/browse_everything/driver/s3.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1277

BLUEDOC-1277 - Add unit tests and update coverage stats

---

app/jobs/register_doi_job.rb
app/services/deepblue/datacite_registrar.rb
app/services/deepblue/doi_minting_2021_service.rb
app/services/deepblue/doi_minting_service.rb
config/initializers/doi_minting_service_integration.rb
spec/jobs/register_doi_job_spec.rb
spec/services/deepblue/datacite_registrar_spec.rb
spec/services/deepblue/doi_minting_2021_service_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1282

BLUEDOC-1282 - DOI minting remaining in draft

---

app/views/hyrax/base/_attribute_rows.html.erb
spec/views/hyrax/base/_attributes.html.erb_spec.rb

This is in reference to this jira ticket:
https://tools.lib.umich.edu/jira/browse/BLUEDOC-1117

for more than 5 creators, list the creators.

---

app/views/_masthead.html.erb
app/views/layouts/hyrax.html.erb

For this issue:  https://tools.lib.umich.edu/jira/browse/BLUEDOC-1240

add universal header.

---

app/controllers/concerns/hyrax/contact_form_controller.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1286

BLUEDOC-1286 - Contact form not logging

---

app/jobs/export_documentation_job.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1148

BLUEDOC-1148 - Export MetaDoc from production and update github

---

app/controllers/hyrax/data_sets_controller.rb
app/controllers/hyrax/downloads_controller.rb
app/helpers/deepblue/irus_helper.rb
app/helpers/deepblue/json_logger_helper.rb
app/helpers/deepblue/logging_helper.rb
config/application.rb
lib/email_logger.rb
lib/irus_logger.rb
lib/provenance_logger.rb
spec/controllers/hyrax/data_sets_controller_spec.rb
spec/controllers/hyrax/downloads_controller_spec.rb
spec/helpers/deepblue/irus_helper_spec.rb
spec/helpers/deepblue/json_logger_helper_spec.rb
spec/helpers/deepblue/provenance_helper_spec.rb
spec/lib/email_logger_spec.rb
spec/lib/hyrax/contact_form_logger_spec.rb
spec/lib/irus_logger_spec.rb
spec/lib/provenance_logger_spec.rb
spec/lib/scheduler_logger_spec.rb
spec/lib/upload_logger_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1292

BLUEDOC-1292 - Add Irus logger

---

app/controllers/concerns/integrator/hyrax/works_behavior.rb
app/services/willow_sword/integration_service.rb
config/initializers/willow_sword.rb
spec/services/willow_sword/integration_service_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1259

BLUEDOC-1295 - sword config change

---

app/models/concerns/deepblue/email_behavior.rb

This addresses jira ticket: https://tools.lib.umich.edu/jira/browse/BLUEDOC-568

send notification when work is deleted with title.

---

app/assets/stylesheets/application.css
app/assets/stylesheets/custom_layout/umich-design-token.css
app/views/layouts/hyrax.html.erb

I got these tweaks from Bridget.

tweak to get universal header to work.

---

app/controllers/hyrax/data_sets_controller.rb

Fixes issue:  https://mlit.atlassian.net/browse/DEEPBLUE-13

Send email when globus is complete without errors.

---

app/models/concerns/deepblue/metadata_behavior.rb
spec/models/data_set_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-16

DEEPBLUE-16 - Create a metadata description extract

---

app/helpers/deepblue/email_helper.rb
app/helpers/deepblue/job_task_helper.rb
app/helpers/hyrax/embargo_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/globus_copy_job.rb
app/jobs/globus_errors_report_job.rb
app/jobs/globus_status_report_job.rb
app/mailers/deepblue_mailer.rb
app/models/concerns/deepblue/abstract_event_behavior.rb
app/models/concerns/deepblue/email_behavior.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/models/concerns/deepblue/workflow_event_behavior.rb
app/services/deepblue/curation_concern_report_behavior.rb
app/services/deepblue/fedora_accessible_service.rb
lib/tasks/new_content_service.rb
spec/helpers/deepblue/email_helper_spec.rb
spec/models/concerns/deepblue/abstract_event_behavior_spec.rb
spec/models/concerns/deepblue/email_behavior_spec.rb
spec/models/concerns/deepblue/metadata_behavior_spec.rb
spec/models/concerns/deepblue/workflow_event_behavior_spec.rb

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1249
https://mlit.atlassian.net/browse/DEEPBLUE-7

BLUEDOC-1249 - Work published email type should be html

---

app/controllers/contact_form_dashboard_controller.rb
app/controllers/email_dashboard_controller.rb
app/helpers/deepblue/json_logger_helper.rb
app/helpers/deepblue/provenance_helper.rb
app/helpers/hyrax/contact_form_helper.rb
app/helpers/json_helper.rb
app/helpers/view_helper.rb
app/presenters/contact_form_dashboard_presenter.rb
app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/show_contact_form_dashboard.html.erb
app/views/hyrax/dashboard/show_email_dashboard.html.erb
app/views/hyrax/dashboard/sidebar/_tasks.html.erb
config/locales/en.yml
config/locales/hyrax.en.yml
config/routes.rb
lib/hyrax/contact_form_logger.rb
spec/helpers/analytics_helper_spec.rb
spec/helpers/deepblue/provenance_helper_spec.rb
spec/helpers/hyrax/contact_form_helper_spec.rb
spec/helpers/hyrax/file_set_helper_spec.rb
spec/helpers/job_helper_spec.rb
spec/helpers/json_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-20

DEEPBLUE-20 - View contact form log

---

app/controllers/catalog_controller.rb
app/controllers/contact_form_dashboard_controller.rb
app/controllers/google_analytics_dashboard_controller.rb
app/controllers/provenance_log_controller_behavior.rb
app/helpers/json_helper.rb
app/services/deepblue/provenance_path.rb
app/services/deepblue/virus_scan_service.rb
app/views/hyrax/dashboard/show_contact_form_dashboard.html.erb
spec/controllers/catalog_controller_spec.rb
spec/controllers/contact_form_dashboard_controller_spec.rb
spec/controllers/google_analytics_dashboard_controller_spec.rb
spec/controllers/guest_user_message_controller_spec.rb
spec/controllers/hyrax/static_controller_spec.rb
spec/controllers/ingest_dashboard_controller_spec.rb
spec/controllers/provenance_log_controller_behavior_spec.rb
spec/controllers/provenance_log_controller_spec.rb
spec/controllers/report_dashboard_controller_spec.rb
spec/controllers/scheduler_dashboard_controller_spec.rb
spec/controllers/work_view_content_controller_spec.rb
spec/controllers/work_view_documentation_controller_spec.rb
spec/helpers/hyrax/contact_form_helper_spec.rb
spec/helpers/json_helper_spec.rb
spec/services/deepblue/provenance_log_service_spec.rb
spec/services/deepblue/provenance_path_spec.rb
spec/services/deepblue/uptime_service_spec.rb
spec/services/deepblue/virus_scan_service_spec.rb
spec/services/deepblue/work_view_content_service_spec.rb
spec/services/deepblue/zip_download_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-20

DEEPBLUE-20 - View contact form log 3

---

app/controllers/concerns/hyrax/contact_form_controller.rb
app/controllers/contact_form_dashboard_controller.rb
app/controllers/job_statuses_controller.rb
app/helpers/application_helper.rb
app/models/concerns/deepblue/abstract_event_behavior.rb
app/presenters/job_statuses_presenter.rb
app/services/deepblue/cache_service.rb
app/views/hyrax/dashboard/show_contact_form_dashboard.html.erb
app/views/job_statuses/index.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/job_statuses_controller_spec.rb
spec/controllers/job_workers_controller_spec.rb
spec/services/deepblue/cache_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-20

DEEPBLUE-20 - View contact form log 4

---

app/services/deepblue/search_service_depositor_works.rb

https://mlit.atlassian.net/browse/DEEPBLUE-23

DEEPBLUE-23 - Error in search service depositor work

---

app/controllers/hyrax/collections_controller.rb
app/controllers/hyrax/data_sets_controller.rb
app/controllers/hyrax/my/collections_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-24

Deepblue 24 fix redirect to back

---

app/views/hyrax/base/show.html.erb

Fix based on comment on:  
https://tools.lib.umich.edu/jira/browse/BLUEDOC-1037

change to have DataCite badge show up.

---

app/controllers/job_statuses_controller.rb
app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/sidebar/_tasks.html.erb
app/views/job_statuses/index.html.erb
config/locales/hyrax.en.yml
config/routes.rb

https://mlit.atlassian.net/browse/DEEPBLUE-26

DEEPBLUE-26 - Add date filtering to job statuses page

---

app/views/hyrax/collections/show.html.erb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-32

move collection metadata below description

---

app/assets/stylesheets/custom_layout/tweaks.css
app/views/shared/_footer.html.erb

Fixes : [DEEPBLUE-31](https://mlit.atlassian.net/browse/DEEPBLUE-31)

change footer to look like doc's footer.

---

app/jobs/find_and_fix_empty_file_sizes_behavior.rb
app/services/deepblue/find_and_fix_service.rb
config/initializers/find_and_fix_service_integration.rb
spec/services/deepblue/find_and_fix_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-30

DEEPBLUE-30 - Update find and fix for file sizes

---

app/controllers/job_statuses_controller.rb
app/helpers/json_helper.rb
app/models/job_status.rb
app/models/proxy_deposit_request.rb
app/presenters/job_statuses_presenter.rb
app/views/_user_util_links.html.erb
app/views/email_subscriptions/index.html.erb
app/views/job_statuses/index.html.erb
app/views/job_statuses/show.html.erb
app/views/roles/index.html.erb
spec/services/deepblue/find_and_fix_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-26

DEEPBLUE-26 - Add date filtering to job statuses page - 2

---

app/helpers/analytics_helper.rb

Fixes : [DEEPBLUE-38](https://mlit.atlassian.net/browse/DEEPBLUE-38)
There seems to be visits from the same ip address that are getting new entries in the Ahoy::Visit table. This code adds a check for counts based on ip addresses.  More than 50 visits on the same file during a month from the same ip address will not be counted.

do some more filtering of stats based on ip values.

---

app/controllers/work_view_documentation_controller.rb
app/services/deepblue/email_templates_loader.rb
app/services/deepblue/i18n_templates_loader.rb
app/services/deepblue/sitemap_generator_service.rb
app/services/deepblue/threaded_var_service.rb
app/services/deepblue/view_templates_loader.rb
app/services/server_after_initialize_service.rb
app/views/_masthead_announcement.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-42

Deepblue 42 metadoc changes do not propagate across threads

---

app/views/_masthead_announcement.html.erb
config/application.rb

https://mlit.atlassian.net/browse/DEEPBLUE-42

DEEPBLUE-42 - MetaDoc changes do not propagate across threads 2

---

app/jobs/doi_pending_report_job.rb
app/services/deepblue/abstract_reporter.rb
app/services/deepblue/doi_minting_service.rb
app/services/deepblue/doi_pending_reporter.rb
app/services/deepblue/globus_reporter.rb
app/services/deepblue/threaded_var_service.rb
lib/tasks/abstract_report_task.rb
lib/tasks/doi_pending_report.rake
lib/tasks/doi_pending_report_task.rb
lib/tasks/globus_errors_report.rake
lib/tasks/globus_errors_report.rb
lib/tasks/globus_status_report.rake
spec/tasks/doi_pending_report_rake_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-10

DEEPBLUE-10 - Add DOI in-progress check/report to the find and fix job

---

app/helpers/analytics_helper.rb

fixes https://mlit.atlassian.net/browse/DEEPBLUE-41

additional check for stats.

---

app/views/records/edit_fields/_creator.html.erb

This is related to this issue: https://mlit.atlassian.net/browse/DEEPBLUE-33

add a place holder for creator field in input page.

---

app/helpers/persist_helper.rb
app/models/concerns/hyrax/ability.rb
app/services/hyrax/workflow/status_list_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-48

DEEPBLUE-48 - Review Submission page off Dashboard failing

---

app/indexers/hyrax/admin_set_indexer.rb

The Admin titles were not showing up on the collection dashboard.

have admin title show up on dashboard.

---

Gemfile
Gemfile.lock
app/presenters/scheduler_dashboard_presenter.rb
app/views/hyrax/dashboard/show_scheduler_dashboard.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-54

DEEPBLUE-54 - Update manage scheduler dashboard

---

app/presenters/hyrax/presents_attributes.rb

Fixes : https://mlit.atlassian.net/browse/DEEPBLUE-58

make more than 5 authors show up as para in work page.

---

app/models/concerns/umrdr/solr_document_behavior.rb
app/views/hyrax/base/_attribute_rows.html.erb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-60

allow for multiple fundedby_other to be displayed.

---

app/helpers/deepblue/interpolation_helper.rb
spec/helpers/deepblue/file_content_helper_spec.rb
spec/helpers/deepblue/ingest_helper_spec.rb
spec/helpers/deepblue/interpolation_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-61

DEEPBLUE-61 - User guide load broken

---

app/views/hyrax/dashboard/_my_active_embargoes.html.erb
app/views/hyrax/my/works/index.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-63

DEEPBLUE-63 - Add active embargo to works page

---

Gemfile
Gemfile.lock
app/controllers/browse_everything_controller.rb
app/services/browse_everything_integration_service.rb
config/initializers/browse_everything_service_integration.rb
lib/browse_everything/driver/authentication_factory.rb
lib/browse_everything/driver/base.rb
lib/browse_everything/driver/dropbox.rb

https://mlit.atlassian.net/browse/DEEPBLUE-68

DEEPBLUE-68 - Add from cloud (dropbox) is not working

---

app/controllers/browse_everything_controller.rb
app/services/browse_everything_integration_service.rb
app/views/browse_everything/_auth.html.erb
app/views/browse_everything/_files.html.erb
app/views/browse_everything/index.html.erb
config/initializers/browse_everything_service_integration.rb
lib/browse_everything/browser.rb
lib/browse_everything/driver/base.rb
lib/browse_everything/driver/dropbox.rb
spec/services/browse_everything_integration_service_spec.rb
spec/services/deepblue/ingest_content_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-68

DEEPBLUE-68 - Add from cloud (dropbox) is not working - 2

---

app/helpers/hyrax/branding_helper.rb
app/services/server_after_initialize_service.rb
spec/helpers/hyrax/branding_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-72

DEEPBLUE-72 - Automate public branding dir link

---

app/helpers/deepblue/clean_up_helper.rb
app/helpers/deepblue/job_task_helper.rb
app/helpers/hyrax/branding_helper.rb
app/jobs/clean_blacklight_query_cache_job.rb
app/jobs/export_log_files_job.rb
lib/tasks/clean_blacklight_query_cache.rake
lib/tasks/clean_blacklight_query_cache_task.rb
lib/tasks/export_log_files.rake

https://mlit.atlassian.net/browse/DEEPBLUE-74

DEEPBLUE-74 - Improved clean blacklight query cache task and job

---

app/helpers/deepblue/find_and_fix_helper.rb
app/services/deepblue/abstract_fixer.rb
app/services/deepblue/file_sets_lost_and_found_fixer.rb
app/services/deepblue/file_sets_visibility_fixer.rb
app/services/deepblue/find_and_fix_service.rb
app/services/deepblue/works_ordered_members_file_sets_size_fixer.rb
app/services/deepblue/works_ordered_members_nils_fixer.rb
app/services/deepblue/works_total_file_size_fixer.rb
config/initializers/find_and_fix_service_integration.rb
spec/actors/hyrax/actors/file_set_actor_spec.rb
spec/services/deepblue/abstract_fixer_spec.rb
spec/services/deepblue/find_and_fix_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-76

DEEPBLUE-76 - Add find and fix work total file size

---

app/views/hyrax/dashboard/_draft_works.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-78

when add works is disabled, don't allow draft works to be deleted.

---

app/jobs/doi_pending_report_job.rb
app/jobs/globus_errors_report_job.rb
app/jobs/globus_status_report_job.rb
app/services/deepblue/abstract_reporter.rb
app/services/deepblue/abstract_service.rb
app/services/deepblue/curation_concern_report_behavior.rb
app/services/deepblue/curation_concern_reporter.rb
app/services/deepblue/doi_minting_service.rb
app/services/deepblue/doi_pending_reporter.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_reporter.rb
app/services/deepblue/message_handler.rb
app/services/deepblue/work_impact_reporter.rb
app/services/deepblue/works_reporter.rb
lib/tasks/about_to_expire_embargoes_task.rb
lib/tasks/abstract_task.rb
lib/tasks/curation_concern_report_task.rb
lib/tasks/deactivate_expired_embargoes_task.rake
lib/tasks/doi_pending_report_task.rb
lib/tasks/globus_errors_report.rake
lib/tasks/globus_errors_report.rb
lib/tasks/globus_status_report.rake
lib/tasks/globus_status_report.rb
lib/tasks/work_impact_report_task.rb
lib/tasks/works_report.rake
spec/services/deepblue/abstract_service_spec.rb
spec/services/deepblue/message_handler_spec.rb
spec/tasks/doi_pending_report_rake_spec.rb
spec/tasks/globus_errors_report_rake_spec.rb
spec/tasks/globus_status_report_rake_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-80

DEEPBLUE-80 - Impact report

---

app/helpers/deepblue/report_helper.rb
app/helpers/hyrax/embargo_helper.rb
app/jobs/about_to_expire_embargoes_job.rb
app/services/deepblue/about_to_expire_embargoes_service.rb
app/services/deepblue/curation_concern_report_behavior.rb
app/services/deepblue/message_handler.rb
app/services/deepblue/work_impact_reporter.rb
lib/ldp/response.rb
lib/tasks/about_to_expire_embargoes_task.rb
lib/tasks/abstract_task.rb
lib/tasks/curation_concern_report_task.rb
lib/tasks/work_impact_report.rake
lib/tasks/work_impact_report_task.rb
lib/tasks/works_report.rake
lib/tasks/works_report_task.rb
spec/helpers/deepblue/report_helper_spec.rb
spec/jobs/about_to_expire_embargoes_job_spec.rb
spec/services/deepblue/about_to_expire_embargoes_service_spec.rb
spec/tasks/about_to_expire_embargoes_task_rake_spec.rb
spec/tasks/about_to_expire_embargoes_task_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-80

DEEPBLUE-80 - Impact report - 2

---

app/jobs/ingest_script_job.rb
app/services/deepblue/ingest_content_service.rb
spec/jobs/ingest_script_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-82

DEEPBLUE-82 - Email results from append to work - 2

---

app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/jobs/doi_minting_job.rb
app/jobs/ensure_doi_minted_job.rb
app/jobs/export_documentation_job.rb
app/jobs/ingest_script_job.rb
app/jobs/work_find_and_fix_job.rb

https://mlit.atlassian.net/browse/DEEPBLUE-82

DEEPBLUE-82 - Email results from append to work - 3

---

app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/jobs/doi_minting_job.rb
app/jobs/ensure_doi_minted_job.rb
app/jobs/export_documentation_job.rb
app/jobs/ingest_script_job.rb
app/jobs/work_find_and_fix_job.rb

https://mlit.atlassian.net/browse/DEEPBLUE-82

Deepblue 82 email results from append to work 4

---

app/controllers/job_statuses_controller.rb
app/presenters/job_statuses_presenter.rb
app/views/hyrax/base/_job_statuses_actions.html.erb
app/views/job_statuses/show.html.erb
app/views/shared/_job_status_cc.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-85

DEEPBLUE-85 - Add links to job status records from work page

---

app/jobs/ingest_script_job.rb
app/services/deepblue/ingest_content_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-87

DEEPBLUE-87 - Work append script fails

---

app/views/catalog/_document.html.erb
app/views/layouts/_head_tag_content.html.erb

This addresses some google indexing issues that were reported.  It is related to this PR:
https://github.com/mlibrary/deepblue/pull/1128

improve google scholar index

---

app/actors/hyrax/actors/base_actor.rb
app/helpers/analytics_helper.rb
app/jobs/update_condensed_events_job.rb
app/services/deepblue/analytics_integration_service.rb
app/services/deepblue/message_handler.rb
app/services/deepblue/message_handler_debug_only.rb
app/services/deepblue/message_handler_null.rb
app/services/deepblue/work_impact_reporter.rb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_list_works.html.erb
config/initializers/analytics_integration.rb
spec/helpers/analytics_helper_spec.rb
spec/jobs/update_condensed_events_job_spec.rb
spec/services/deepblue/analytics_integration_service_spec.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report

---

app/helpers/analytics_helper.rb
app/helpers/deepblue/report_helper.rb
app/services/deepblue/analytics_integration_service.rb
app/services/deepblue/message_handler.rb
app/services/deepblue/message_handler_queue_to_file.rb
app/services/deepblue/work_impact_reporter.rb
config/initializers/analytics_integration.rb
lib/tasks/work_impact_report.rake
spec/helpers/analytics_helper_spec.rb
spec/services/deepblue/analytics_integration_service_spec.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 2

---

app/helpers/analytics_helper.rb
lib/tasks/initialize_condensed_events_downloads.rake
lib/tasks/initialize_condensed_events_downloads_task.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 3

---

app/helpers/analytics_helper.rb
app/helpers/msg_helper.rb
app/services/deepblue/message_handler_queue_to_file.rb
spec/jobs/find_and_fix_job_spec.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 5

---

app/helpers/analytics_helper.rb
config/initializers/analytics_integration.rb
lib/tasks/initialize_condensed_events_downloads.rake
lib/tasks/initialize_condensed_events_downloads_task.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 6

---

Gemfile
Gemfile.lock

https://mlit.atlassian.net/browse/DEEPBLUE-99

DEEPBLUE-99 - Revert to hyrax 3.0.1 and upgrade gems - 3

---

app/helpers/analytics_helper.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 7

---

app/helpers/analytics_helper.rb
app/jobs/update_condensed_events_job.rb
app/services/deepblue/abstract_service.rb
app/services/deepblue/message_handler_null.rb
lib/tasks/update_condensed_events.rake
lib/tasks/update_condensed_events_task.rb
lib/tasks/work_find_and_fix.rake
spec/helpers/analytics_helper_spec.rb

DEEPBLUE-98 - Add file sets downloaded to work impact report - 8

---

app/views/hyrax/base/_attribute_rows.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-100

DEEPBLUE-100 - Other license link throws an error

---

Gemfile.lock

https://mlit.atlassian.net/browse/DEEPBLUE-99

DEEPBLUE-99 - Revert to hyrax 3.0.1 and upgrade gems - 4

---

app/helpers/deepblue/job_task_helper.rb
app/jobs/fedora_accessible_job.rb
app/jobs/work_impact_report_job.rb
app/jobs/works_report_job.rb
spec/jobs/work_impact_report_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-104

DEEPBLUE-104 - Add impact work report job and add to scheduler

---

app/controllers/hyrax/data_sets_controller.rb
app/presenters/hyrax/data_set_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb
spec/views/hyrax/base/_attributes.html.erb_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-100

DEEPBLUE-100 - Other license link throws an error - 3

---

Gemfile
Gemfile.lock
app/helpers/deepblue/teamdynamix_helper.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml

DEEPBLUE-37 - Create tickets in TeamDynamix

---

app/presenters/deepblue/total_file_size_presenter_behavior.rb
app/views/hyrax/base/_show_actions.html.erb
spec/views/hyrax/base/_show_actions.html.erb_spec.rb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-107

disable download file buttons if there are no files.

---

app/views/catalog/_search_form.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-109

display drop down options for search on home page.

---

Gemfile
Gemfile.lock
app/helpers/deepblue/jira_helper.rb
app/helpers/deepblue/teamdynamix_helper.rb
config/initializers/teamdynamix_integration.rb
lib/hydra/derivatives/processors/document.rb
spec/helpers/deepblue/teamdynamix_helper_spec.rb

DEEPBLUE-37 - Create tickets in TeamDynamix - 2

---

app/helpers/deepblue/teamdynamix_helper.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml

DEEPBLUE-37 - Create tickets in TeamDynamix - 3

---

config/environments/production.rb

https://mlit.atlassian.net/browse/DEEPBLUE-119

DEEPBLUE-119 - Shift action mailer to use sendmail

---

app/controllers/email_dashboard_controller.rb
app/controllers/hyrax/downloads_controller.rb
app/helpers/analytics_helper.rb
app/helpers/deepblue/email_helper.rb
app/helpers/deepblue/job_task_helper.rb
app/helpers/deepblue/log_file_helper.rb
app/helpers/hyrax/embargo_helper.rb
app/helpers/json_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/globus_copy_job.rb
app/services/deepblue/email_subscription_service.rb
config/routes.rb
spec/services/deepblue/email_subscription_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-118

DEEPBLUE-118 - Add resend button for email in email log

---

app/jobs/copy_logs_dir_job.rb
app/services/server_logs_copy_service.rb
config/initializers/logging_initialization_service_integration.rb
spec/services/deepblue/logging_initialization_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-124

DEEPBLUE-124 - Add copy logs job

---

app/controllers/scheduler_dashboard_controller.rb
app/helpers/deepblue/export_files_helper.rb
app/jobs/copy_logs_dir_job.rb
app/services/deepblue/scheduler_integration_service.rb
app/services/server_logs_copy_service.rb
config/initializers/resque_config.rb
config/initializers/scheduler_service_integration.rb

https://mlit.atlassian.net/browse/DEEPBLUE-124

DEEPBLUE-124 - Add copy logs job - 1

---

app/controllers/concerns/deepblue/works_controller_behavior.rb
app/controllers/hyrax/data_sets_controller.rb
app/helpers/deepblue/jira_helper.rb
app/jobs/new_service_request_ticket_job.rb
app/models/concerns/deepblue/metadata_behavior.rb
app/presenters/hyrax/work_show_presenter.rb
app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
app/views/hyrax/base/_show_actions.html.erb
config/initializers/teamdynamix_service_integration.rb
config/locales/data_set.en.yml
config/routes.rb

DEEPBLUE-37 - Create tickets in TeamDynamix - 5

---

app/services/deepblue/teamdynamix_service.rb
config/initializers/teamdynamix_service_integration.rb

DEEPBLUE-37 - Create tickets in TeamDynamix - 6

---

app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
config/initializers/teamdynamix_service_integration.rb
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml

DEEPBLUE-37 - Create tickets in TeamDynamix - 7

---

app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
config/initializers/teamdynamix_service_integration.rb

DEEPBLUE-37 - Create tickets in TeamDynamix - 8

---

app/services/deepblue/teamdynamix_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-137

DEEPBLUE-137 - Teamdynamix REST update wiping out custom fields

---

app/jobs/new_service_request_ticket_job.rb
app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
config/initializers/teamdynamix_service_integration.rb

https://mlit.atlassian.net/browse/DEEPBLUE-138

DEEPBLUE-138 - Update teamdynamix tickets with custom attributes

---

app/presenters/work_view_documentation_presenter.rb

https://mlit.atlassian.net/browse/DEEPBLUE-141

DEEPBLUE-141 - Fix display of doc management dashboard screen

---

Gemfile
Gemfile.lock

https://mlit.atlassian.net/browse/DEEPBLUE-142

DEEPBLUE-142 - Fix selenium testing

---

app/controllers/concerns/hyrax/contact_form_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-143

DEEPBLUE-143 - Contact form umich.edu passthrough not working

---

app/controllers/concerns/deepblue/works_controller_behavior.rb
app/controllers/concerns/hyrax/collections_controller_behavior.rb
app/controllers/hyrax/collections_controller.rb
app/controllers/hyrax/dashboard/collections_controller.rb
app/controllers/hyrax/file_sets_controller.rb
app/controllers/hyrax/my/collections_controller.rb
app/controllers/provenance_log_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-144

DEEPBLUE-144 - Unknown work id page throwing error

---

app/views/layouts/hyrax.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-146

switching web components for header in data.

---

app/views/hyrax/base/_member.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-139

remove title from file list on work page

---

app/models/collection_branding_info.rb

Fixes issue:  https://mlit.atlassian.net/browse/DEEPBLUE-145
This was an issue that I fixed when I worked on a hyrax sprint.

saving collection branding throws an error.

---

app/services/deepblue/curation_concern_report_behavior.rb
lib/tasks/collections_report.rake
lib/tasks/curation_concern_report_task.rb
lib/tasks/curation_concerns_report.rake
lib/tasks/works_report_task.rb

https://mlit.atlassian.net/browse/DEEPBLUE-149

DEEPBLUE-149 - Works report error for sippity conversion

---

app/assets/stylesheets/custom_layout/tweaks.css
app/views/hyrax/base/_items.html.erb

Fixes https://mlit.atlassian.net/browse/DEEPBLUE-150

change file list header size

---

app/actors/hyrax/actors/initialize_workflow_actor.rb
app/helpers/deepblue/find_and_fix_helper.rb
app/jobs/find_and_fix_job.rb
app/jobs/work_find_and_fix_job.rb
app/services/deepblue/abstract_fixer.rb
app/services/deepblue/draft_admin_set_service.rb
app/services/deepblue/file_sets_embargo_fixer.rb
app/services/deepblue/file_sets_lost_and_found_fixer.rb
app/services/deepblue/find_and_fix.rb
app/services/deepblue/find_and_fix_curation_concern_filter_date.rb
app/services/deepblue/find_and_fix_service.rb
app/services/deepblue/works_ordered_members_file_sets_size_fixer.rb
app/services/deepblue/works_ordered_members_nils_fixer.rb
app/services/deepblue/works_total_file_size_fixer.rb
config/initializers/find_and_fix_service_integration.rb
lib/tasks/work_find_and_fix_task.rb
spec/services/deepblue/abstract_fixer_spec.rb
spec/services/deepblue/file_sets_lost_and_found_fixer_spec.rb
spec/services/deepblue/file_sets_visibility_fixer_spec.rb
spec/services/deepblue/find_and_fix_spec.rb
spec/services/deepblue/works_ordered_members_file_sets_size_fixer_spec.rb
spec/services/deepblue/works_ordered_members_nils_fixer_spec.rb
spec/tasks/work_find_and_fix_task_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-125

DEEPBLUE-125 - Add file set out of sync embargo status to find and fix

---

app/controllers/globus_dashboard_controller.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_status.rb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
config/locales/hyrax.en.yml

DEEPBLUE-147 - Globus dashboard - 2

---

app/controllers/globus_dashboard_controller.rb
app/helpers/config_helper.rb
app/presenters/globus_dashboard_presenter.rb
app/services/deepblue/globus_integration_service.rb
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/dashboard/_globus_dashboard_work_form.html.erb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
app/views/hyrax/dashboard/show_scheduler_dashboard.html.erb
config/initializers/globus_service_integration.rb
config/locales/hyrax.en.yml

DEEPBLUE-147 - Globus dashboard - 4

---

app/controllers/globus_dashboard_controller.rb
app/presenters/globus_dashboard_presenter.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_reporter.rb
app/services/deepblue/globus_status.rb
app/views/hyrax/dashboard/_globus_dashboard_work_form.html.erb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
config/initializers/globus_service_integration.rb
spec/jobs/globus_copy_job_spec.rb
spec/jobs/globus_job_spec.rb
spec/jobs/globus_restart_all_job_spec.rb
spec/tasks/globus_status_report_rake_spec.rb

DEEPBLUE-147 - Globus dashboard - 5

---

app/helpers/persist_helper.rb
app/jobs/globus_job.rb
app/presenters/globus_dashboard_presenter.rb
app/services/deepblue/globus_status.rb
app/views/hyrax/dashboard/_globus_dashboard_work_form.html.erb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
app/views/hyrax/dashboard/works/_default_group.html.erb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_default_group.html.erb
app/views/hyrax/my/works/_list_works.html.erb
app/views/hyrax/my/works/index.html.erb
config/initializers/globus_service_integration.rb
config/locales/hyrax.en.yml

DEEPBLUE-147 - Globus dashboard - 6

---

app/controllers/globus_dashboard_controller.rb
app/presenters/globus_dashboard_presenter.rb
app/views/hyrax/dashboard/_globus_dashboard_work_form.html.erb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_list_works.html.erb

DEEPBLUE-147 - Globus dashboard - 7

---

app/controllers/globus_dashboard_controller.rb
app/controllers/hyrax/data_sets_controller.rb
app/jobs/globus_clean_job.rb
app/jobs/globus_copy_job.rb
app/presenters/globus_dashboard_presenter.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_status.rb
app/views/hyrax/dashboard/show_globus_dashboard.html.erb
config/initializers/globus_service_integration.rb
spec/jobs/globus_copy_job_spec.rb

DEEPBLUE-147 - Globus dashboard - 8

---

app/controllers/globus_dashboard_controller.rb
app/controllers/hyrax/data_sets_controller.rb
app/helpers/deepblue/disk_utilities_helper.rb
app/helpers/deepblue/email_helper.rb
app/helpers/msg_helper.rb
app/jobs/globus_errors_report_job.rb
app/jobs/globus_job.rb
app/jobs/globus_status_report_job.rb
app/models/concerns/umrdr/umrdr_work_behavior.rb
app/presenters/globus_dashboard_presenter.rb
app/presenters/hyrax/data_set_presenter.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_service.rb
app/services/deepblue/globus_status.rb
app/views/hyrax/dashboard/_globus_dashboard_work_form.html.erb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_list_works.html.erb
lib/tasks/globus_errors_report.rb
lib/tasks/globus_status_report.rb
spec/jobs/globus_job_spec.rb
spec/tasks/globus_errors_report_rake_spec.rb
spec/tasks/globus_status_report_rake_spec.rb

DEEPBLUE-147 - Globus dashboard - 9

---

app/jobs/globus_copy_job.rb
app/services/deepblue/globus_integration_service.rb
app/services/deepblue/globus_service.rb
config/initializers/globus_service_integration.rb

DEEPBLUE-147 - Globus dashboard - 10

---

app/views/hyrax/collections/_search_form.html.erb
app/views/hyrax/homepage/_marketing.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-162

replace i (italic) tag with em

---

Gemfile
Gemfile.lock
app/controllers/browse_everything_controller.rb
app/helpers/deepblue/logging_helper.rb
app/services/deepblue/message_handler.rb
app/services/deepblue/message_handler_null.rb
db/migrate/20220429201416_update_single_use_links_column_names.hyrax.rb
lib/browse_everything/driver/base.rb
lib/browse_everything/driver/dropbox.rb

https://mlit.atlassian.net/browse/DEEPBLUE-158

DEEPBLUE-158 - Fix dropbox connection

---

app/assets/stylesheets/custom_layout/tweaks.css

Fixes https://mlit.atlassian.net/browse/DEEPBLUE-148

changing font-size to 16px on work page.

---

app/views/job_statuses/index.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-88

DEEPBLUE-88 - Header row on job statuses table missing

---

app/helpers/deepblue/file_content_helper.rb
app/helpers/deepblue/metadata_helper.rb
app/renderers/hyrax/renderers/attribute_renderer.rb

https://mlit.atlassian.net/browse/DEEPBLUE-105

DEEPBLUE-105 - Some metadata field displays are failing

---

app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/actors/hyrax/actors/ordered_members_actor.rb
app/helpers/deepblue/export_files_helper.rb
app/helpers/deepblue/ingest_helper.rb
app/models/concerns/deepblue/file_set_behavior.rb
app/models/concerns/deepblue/ticket_behavior.rb
app/models/concerns/umrdr/solr_document_behavior.rb
app/services/deepblue/virus_scan_service.rb
app/services/hyrax/virus_checker_service.rb
app/views/browse_everything/_auth.html.erb
app/views/browse_everything/_files.html.erb
app/views/browse_everything/index.html.erb
config/application.rb
config/initializers/clamav.rb
config/initializers/hyrax_callbacks.rb
lib/abstract_virus_scanner.rb
lib/null_virus_scanner.rb
lib/umich_clamav_daemon_scanner.rb
spec/services/deepblue/virus_scan_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-167

DEEPBLUE-167 - Virus checker has memory leak

---

app/controllers/concerns/hyrax/contact_form_controller.rb
spec/controllers/hyrax/contact_form_controller_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-123

DEEPBLUE-123 - Tweak email spam filter

---

app/controllers/hyrax/file_sets_controller.rb
app/helpers/persist_helper.rb
app/views/hyrax/base/_modal_move_file_from_work.html.erb
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/file_sets/_show_admin_actions.html.erb
config/locales/data_set.en.yml
config/locales/hyrax.en.yml
config/routes.rb

Fixes https://mlit.atlassian.net/browse/DEEPBLUE-66

allow files to be moved to a different work.

---

app/helpers/deepblue/find_and_fix_helper.rb
app/services/deepblue/works_total_file_size_fixer.rb
lib/tasks/new_content_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-168

DEEPBLUE-168 - find and fix fails to fix solr 0 size file set sizes

---

lib/tasks/new_content_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-169

DEEPBLUE-169 - Update new content service to add more error logging

---

Gemfile
Gemfile.lock

https://mlit.atlassian.net/browse/DEEPBLUE-170

DEEPBLUE-170 - Update gem versions

---

app/assets/javascripts/validations.js
app/controllers/concerns/hyrax/contact_form_controller.rb
app/views/hyrax/base/_form_progress.html.erb
config/locales/data_set.en.yml

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-179
One thing to remember is the great use of 
console.log("Message goes here")
to debut javascript.

add button on deposit page to contact us.

---

app/assets/stylesheets/main.scss
app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/helpers/deepblue/job_task_helper.rb
app/helpers/deepblue/jobs_helper.rb
app/models/ingest_script.rb
app/presenters/hyrax/data_set_presenter.rb
app/services/deepblue/ingest_append_content_service.rb
app/views/data_set/_ingest_append_script_files.html.erb
app/views/data_set/_ingest_append_script_files_widget.html.erb
app/views/data_set/_ingest_append_script_view_fields.html.erb
app/views/hyrax/base/_show_work_body.html.erb
app/views/hyrax/dashboard/show_admin.html.erb
app/views/hyrax/dashboard/show_scheduler_dashboard.html.erb
config/locales/hyrax.en.yml

https://mlit.atlassian.net/browse/DEEPBLUE-178

DEEPBLUE-178 - Show run and running append scripts on work pages

---

app/helpers/deepblue/jobs_helper.rb
app/helpers/job_helper.rb
app/jobs/deepblue/deepblue_job.rb
app/jobs/file_monitor_job.rb
app/jobs/ingest_append_script_monitor_job.rb
app/jobs/job_monitor_job.rb
app/jobs/list_arguments_job.rb
app/jobs/scheduler_start_job.rb
app/jobs/sleep_job.rb
app/services/deepblue/ingest_append_content_service.rb
spec/jobs/globus_errors_report_job_spec.rb
spec/jobs/globus_status_report_job_spec.rb
spec/jobs/heartbeat_email_job_spec.rb
spec/jobs/heartbeat_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-175

DEEPBLUE-175 - Add automatic restart of append scripts that fail - 1

---

app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/helpers/deepblue/jobs_helper.rb
app/helpers/job_helper.rb
app/jobs/ingest_append_script_job.rb
app/jobs/ingest_append_script_monitor_job.rb
app/jobs/multiple_ingest_scripts_job.rb
app/models/ingest_script.rb
app/services/deepblue/ingest_append_content_service.rb
app/services/deepblue/new_content_append_service.rb
app/views/hyrax/dashboard/show_admin.html.erb
app/views/hyrax/dashboard/show_scheduler_dashboard.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-175

DEEPBLUE-175 - Add automatic restart of append scripts that fail - 2

---

app/helpers/deepblue/find_and_fix_helper.rb
app/jobs/ingest_append_script_monitor_job.rb

https://mlit.atlassian.net/browse/DEEPBLUE-175

DEEPBLUE-175 - Add automatic restart of append scripts that fail - 3a

---

app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/models/ingest_script.rb
app/presenters/hyrax/data_set_presenter.rb
app/services/deepblue/ingest_content_service.rb
app/services/deepblue/ingest_integration_service.rb
app/services/deepblue/new_content_append_service.rb
app/views/data_set/_ingest_append_script_files.html.erb
app/views/hyrax/data_sets/_ingest_append_script_view.html.erb
config/initializers/ingest_service_integration.rb
spec/controllers/concerns/deepblue/ingest_append_script_controller_behavior_spec.rb
spec/models/ingest_script_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-181

DEEPBLUE-181 - Add manual append script restart - 1a

---

app/views/hyrax/static/rest-api.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-160

DEEPBLUE-160 - About and Help pages need header correction

---

app/helpers/deepblue/disk_utilities_helper.rb
app/jobs/clean_hyrax_tmp_dir_job.rb
app/services/deepblue/clean_derivatives_dir_service.rb
app/services/deepblue/clean_hyrax_tmp_dir_service.rb
app/services/deepblue/clean_uploads_dir_service.rb
spec/controllers/concerns/deepblue/zip_download_controller_behavior_spec.rb
spec/helpers/deepblue/disk_utilities_helper_spec.rb
spec/services/deepblue/clean_derivatives_dir_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-191

DEEPBLUE-191 - Clean tmp directory in production

---

app/actors/hyrax/actors/doi_actor.rb
app/jobs/register_doi_old_job.rb
app/models/collection.rb
app/models/concerns/deepblue/doi_behavior.rb
app/models/concerns/deepblue/metadata_behavior.rb
app/models/data_set.rb
app/presenters/hyrax/collection_presenter.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/renderers/hyrax/renderers/doi_attribute_renderer.rb
app/services/deepblue/datacite_registrar.rb
app/services/deepblue/doi_minting_service.rb
app/views/layouts/_head_tag_content.html.erb
app/views/records/show_fields/_doi.html.erb
spec/jobs/register_doi_job_spec.rb
spec/models/data_set_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-187

DEEPBLUE-187 - Allow Collections to have / create DOIs 2

---

app/services/deepblue/doi_minting_service.rb
app/services/deepblue/new_content_service2.rb
lib/tasks/new_content_service.rb
spec/services/deepblue/new_content_service2_spec.rb
spec/tasks/new_content_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-194

DEEPBLUE-194 - Deal with DOIs stuck in minting process - 1

---

app/services/hyrax/contact_form_integration_service.rb
config/initializers/contact_form_service_integration.rb

https://mlit.atlassian.net/browse/DEEPBLUE-195

DEEPBLUE-195 - Add @med.umich.edu to contact form pass through

---

app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
spec/services/deepblue/teamdynamix_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-193

DEEPBLUE-193 - Update TeamDynamix API

---

app/helpers/deepblue/find_and_fix_helper.rb
app/services/deepblue/file_sets_file_size_fixer.rb
app/services/deepblue/find_and_fix_service.rb
app/services/deepblue/works_total_file_size_fixer.rb
config/initializers/find_and_fix_service_integration.rb
spec/services/deepblue/find_and_fix_service_spec.rb
spec/services/deepblue/find_and_fix_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-93

DEEPBLUE-93 - Work find and fix not fixing file set sizes

---

app/controllers/concerns/hyrax/contact_form_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-199

DEEPBLUE-199 - Fix contact form in production

---

app/views/catalog/_thumbnail_list_collection.html.erb
app/views/catalog/_thumbnail_list_default.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-200

DEEPBLUE-200 - Fix Go button throwing error in production

---

app/services/deepblue/teamdynamix_integration_service.rb
app/services/deepblue/teamdynamix_service.rb
app/views/catalog/_thumbnail_list_collection.html.erb
app/views/catalog/_thumbnail_list_default.html.erb
config/initializers/teamdynamix_service_integration.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml
spec/services/deepblue/teamdynamix_service_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-93

Deepblue 93 work find and fix not fixing file sizes 2

---

app/helpers/deepblue/ticket_helper.rb
app/jobs/new_service_request_ticket_job.rb
app/services/deepblue/teamdynamix_service.rb
config/initializers/teamdynamix_service_integration.rb

https://mlit.atlassian.net/browse/DEEPBLUE-193

DEEPBLUE-193 - Update TeamDynamix API - 2

---

app/helpers/deepblue_presenter_helper.rb
app/presenters/hyrax/collection_presenter.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/deepblue_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/views/layouts/_head_tag_content.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-203
https://mlit.atlassian.net/browse/DEEPBLUE-204

DEEPBLUE-204 - Description field too long for Google Search indexing

---

app/assets/stylesheets/custom_layout/tweaks.css
app/views/_masthead_announcement.html.erb
spec/views/_masthead_announcement.html.erb_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-208

DEEPBLUE-208 - Update masthead banner

---

app/services/hyrax/collections/nested_collection_query_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-217

DEEPBLUE-217- Issue adding subcollections into collection

---

app/helpers/deepblue/find_and_fix_helper.rb
app/services/deepblue/datacite_registrar.rb
app/services/deepblue/doi_minting_2021_service.rb
app/services/deepblue/file_sets_embargo_fixer.rb
app/services/deepblue/file_sets_file_size_fixer.rb
app/services/deepblue/file_sets_lost_and_found_fixer.rb
app/services/deepblue/file_sets_visibility_fixer.rb
app/services/deepblue/find_and_fix_service.rb
app/services/deepblue/works_file_sets_not_lost_fixer.rb
app/services/deepblue/works_file_sets_visibility_fixer.rb
app/services/deepblue/works_ordered_members_file_sets_size_fixer.rb
app/services/deepblue/works_total_file_size_fixer.rb
config/initializers/find_and_fix_service_integration.rb
spec/services/deepblue/find_and_fix_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-223
https://mlit.atlassian.net/browse/DEEPBLUE-224

Deepblue 224 add hide doi to doi service

---

app/helpers/deepblue/export_files_helper.rb

https://mlit.atlassian.net/browse/DEEPBLUE-196

DEEPBLUE-196 - Fix bug in copy logs job

---

app/assets/stylesheets/custom_layout/tweaks.css
app/controllers/email_dashboard_controller.rb
app/helpers/json_helper.rb
app/views/_provenance_log_entries.html.erb
app/views/_provenance_log_entries2.html.erb
app/views/hyrax/dashboard/show_contact_form_dashboard.html.erb
app/views/hyrax/dashboard/show_email_dashboard.html.erb
spec/helpers/json_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-206

DEEPBLUE-206 - Contact form management display of some entries overflows

---

app/helpers/deepblue/export_files_helper.rb
app/helpers/deepblue/metadata_helper.rb
app/jobs/copy_logs_dir_job.rb
app/jobs/globus_era.rb
app/jobs/multiple_ingest_scripts_job.rb
app/jobs/report_task_job.rb
config/application.rb
config/initializers/ingest_service_integration.rb
lib/tasks/new_content_from_yaml.rb
lib/tasks/yaml_diff.rb
lib/tasks/yaml_update.rb
spec/jobs/multiple_ingest_scripts_job_spec.rb
spec/jobs/report_task_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-225

DEEPBLUE-225 - Shift report output to /deepbluedata-prep

---

app/jobs/hide_doi_job.rb
app/models/concerns/deepblue/abstract_event_behavior.rb
app/models/concerns/deepblue/provenance_behavior.rb
app/services/deepblue/datacite_registrar.rb
app/services/deepblue/doi_minting_service.rb
spec/models/concerns/deepblue/abstract_event_behavior_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-226

DEEPBLUE-226 - Add hide DOI support

---

app/models/data_set.rb
spec/models/data_set_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-228

DEEPBLUE-228 - Add admin id to provenance log metadata for update

---

app/helpers/deepblue/report_helper.rb
app/models/data_set.rb
lib/reports/works_without_tickets_report.yml
lib/tasks/report_task.rb

https://mlit.atlassian.net/browse/DEEPBLUE-229

DEEPBLUE-229 - Check for any submitted works that do not have tickets

---

app/controllers/concerns/hyrax/contact_form_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-205

DEEPBLUE-205 - Contact form email passthrough not working.

---

app/controllers/concerns/hyrax/contact_form_controller.rb

https://mlit.atlassian.net/browse/DEEPBLUE-205

DEEPBLUE-205 - Contact form email passthrough not working. - 2

---

app/helpers/deepblue/log_file_helper.rb
app/views/hyrax/base/_show_work_body.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-234

DEEPBLUE-234 - 'Ingest Append Script' shows up for logged out users

---

app/services/deepblue/ingest_append_content_service.rb
app/services/deepblue/new_content_service2.rb

https://mlit.atlassian.net/browse/DEEPBLUE-238

DEEPBLUE-238 - Fix ingest/append scripting

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/controllers/hyrax/orcid/dashboard/works_controller.rb
app/controllers/hyrax/orcid/users_controller.rb
app/helpers/hyrax/orcid/helper_behavior.rb
app/helpers/hyrax/orcid/route_helper.rb
app/services/hyrax/orcid/strategy/sync_notify.rb
app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/shared/orcid/_works.html.erb
config/application.rb
config/locales/hyrax_orcid.en.yml
config/routes.rb

https://mlit.atlassian.net/browse/DEEPBLUE-239

DEEPBLUE-239 - Install hyrax-orcid gem 2

---

app/controllers/begin_end_date_controller_behavior.rb
app/controllers/contact_form_dashboard_controller.rb
app/controllers/debug_log_dashboard_controller.rb
app/controllers/email_dashboard_controller.rb
app/controllers/provenance_log_controller.rb
app/controllers/provenance_log_controller_behavior.rb
app/presenters/provenance_log_presenter.rb
app/services/deepblue/log_extracter.rb
app/services/deepblue/log_filter.rb
app/services/deepblue/provenance_log_service.rb
app/services/deepblue/works_by_user_id_works_from_log.rb
app/views/_provenance_log_entries2.html.erb
app/views/_provenance_log_works_by_user_id.html.erb
app/views/provenance_log/provenance_log.html.erb
config/locales/data_set.en.yml
config/routes.rb
spec/presenters/provenance_log_presenter_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-246

DEEPBLUE-246 - Add user id as a search type on the provenance log page

---

app/controllers/provenance_log_controller.rb
app/helpers/hyrax/orcid/orcid_helper.rb
app/jobs/hyrax/orcid/perform_identity_strategy_job.rb
app/presenters/provenance_log_presenter.rb
app/services/bolognese/helpers/writers.rb
app/services/bolognese/readers/orcid/hyrax_work_reader.rb
app/services/bolognese/writers/orcid/hyrax_xml_builder.rb
app/services/bolognese/writers/orcid/xml_writer.rb
app/services/hyrax/orcid/identity_strategy_delegator.rb
app/services/hyrax/orcid/work/publisher_service.rb
app/services/hyrax/orcid/work_orcid_extractor.rb
app/services/hyrax/orcid_integration_service.rb
app/views/provenance_log/provenance_log.html.erb
config/initializers/_orcid_service_integration.rb
spec/helpers/orcid_helper_spec.rb
spec/services/bolognese/writers/orcid/xml_writer_spec.rb
spec/services/hyrax/orcid/blacklight/rendering/pipeline_json_extractor_spec.rb
spec/services/hyrax/orcid/identity_strategy_delegator_spec.rb
spec/services/hyrax/orcid/unpublish_work_delegator_spec.rb
spec/services/hyrax/orcid/work/publisher_service_spec.rb
spec/services/hyrax/orcid/work_orcid_extractor_spec.rb
spec/services/hyrax/orcid_service_integration_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-242

DEEPBLUE-242 - Add sandbox ORCID sign in and test - 5

---

app/presenters/hyrax/collection_presenter.rb
app/presenters/hyrax/data_set_presenter.rb
app/presenters/hyrax/ds_file_set_presenter.rb
app/presenters/hyrax/work_show_presenter.rb
app/services/server_after_initialize_service.rb
app/views/_ga.html.erb
app/views/_ga_body.html.erb
app/views/layouts/_head_tag_content.html.erb
app/views/layouts/hyrax.html.erb
app/views/layouts/hyrax/dashboard.html.erb
config/application.rb
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml

https://mlit.atlassian.net/browse/DEEPBLUE-244

DEEPBLUE-244 - Add google analytics 4 tracking code

---

app/controllers/concerns/deepblue/ingest_append_script_controller_behavior.rb
app/jobs/ingest_append_script_job.rb
app/jobs/ingest_append_script_monitor_job.rb
app/services/deepblue/ingest_append_content_service.rb
app/services/deepblue/ingest_integration_service.rb
app/services/deepblue/new_content_append_service.rb
config/initializers/ingest_service_integration.rb
spec/controllers/concerns/deepblue/ingest_append_script_controller_behavior_spec.rb
spec/jobs/ingest_append_script_monitor_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-247

DEEPBLUE-247 - Ingest append is attaching multiple copies of files

---

app/views/_remediation_verbage.html.erb
app/views/hyrax/base/_show_work_body.html.erb
app/views/hyrax/file_sets/show.html.erb
config/locales/en.yml

https://mlit.atlassian.net/browse/DEEPBLUE-249

DEEPBLUE-249 - Metadata remediation language (Data)

---

app/controllers/provenance_log_controller.rb
app/controllers/provenance_log_controller_behavior.rb
app/presenters/provenance_log_presenter.rb
app/services/deepblue/provenance_log_service.rb
app/views/_provenance_log_deleted.html.erb
config/application.rb

https://mlit.atlassian.net/browse/DEEPBLUE-246

DEEPBLUE-246 - Add user id as a search type on the provenance log page-2

---

app/controllers/provenance_log_controller.rb
app/services/deepblue/log_filter.rb
app/services/deepblue/provenance_log_service.rb
app/services/deepblue/works_by_user_id_works_from_log.rb

https://mlit.atlassian.net/browse/DEEPBLUE-246

DEEPBLUE-246 - Add user id as a search type on the provenance log page-3

---

app/helpers/deepblue/job_task_helper.rb
app/jobs/fedora_check_and_update_index_job.rb
app/services/deepblue/fedora_accessible_service.rb
config/initializers/new_framework_defaults.rb

https://mlit.atlassian.net/browse/DEEPBLUE-253

DEEPBLUE-253 - Add Fedora index monitor and fix job

---

app/assets/javascripts/hyrax/proxy_rights.js

https://mlit.atlassian.net/browse/DEEPBLUE-243

DEEPBLUE-243 - Can't add a proxy user

---

app/assets/stylesheets/custom_layout/tweaks.css
app/views/_masthead.html.erb
app/views/_subheader.html.erb
config/features.rb
config/locales/hyrax.en.yml

https://mlit.atlassian.net/browse/DEEPBLUE-255

DEEPBLUE-255 - Add subheader for long term announcements

---

config/locales/data_set.en.yml

https://mlit.atlassian.net/browse/DEEPBLUE-256

DEEPBLUE-256 - Add text to Creator ORCID field

---

app/controllers/concerns/deepblue/works_controller_behavior.rb
app/helpers/deepblue/logging_helper.rb
app/jobs/delete_file_sets_from_work_job.rb
app/jobs/fedora_accessible_job.rb
app/jobs/fedora_check_and_update_index_job.rb
app/services/deepblue/fedora_accessible_service.rb
app/views/hyrax/base/_form_uploaded.html.erb
app/views/hyrax/base/_items_no_action.html.erb
app/views/hyrax/base/_member.html.erb
app/views/hyrax/base/_member_no_action.html.erb
spec/helpers/deepblue/logging_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-251

DEEPBLUE-251 - Add bulk file delete in a DataSet

---

app/actors/hyrax/actors/file_set_actor.rb
app/assets/javascripts/hyrax/save_work/save_work_control.es6
app/assets/stylesheets/custom_layout/tweaks.css
app/controllers/concerns/deepblue/works_controller_behavior.rb
app/jobs/delete_file_sets_from_work_job.rb
app/presenters/hyrax/work_show_presenter.rb
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_items_no_action.html.erb
app/views/hyrax/base/_member_no_action.html.erb
app/views/layouts/_head_tag_content.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-251

DEEPBLUE-251 - Add bulk file delete in a DataSet 2a

---

app/assets/stylesheets/main.scss
app/models/concerns/umrdr/solr_document_behavior.rb
app/renderers/hyrax/renderers/creator_orcid_attribute_renderer.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/hyrax/base/_metadata.html.erb
spec/renderers/hyrax/renderers/creator_attribute_renderer_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-261

DEEPBLUE-261 - Multiple ORCIDs are only displaying one on works

---

app/views/_user_util_links.html.erb
app/views/hyrax/base/_form_files.html.erb
app/views/hyrax/collections/_search_form.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/show.html.erb
app/views/hyrax/static/_about_sidebar.html.erb
app/views/hyrax/static/_help_sidebar.html.erb
app/views/hyrax/static/_work_view_content_menu_from_txt.html.erb
app/views/hyrax/static/_work_view_content_menu_from_yml.html.erb
spec/views/_user_util_links.html.erb_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-262
https://mlit.atlassian.net/browse/DEEPBLUE-264
https://mlit.atlassian.net/browse/DEEPBLUE-265
https://mlit.atlassian.net/browse/DEEPBLUE-262

DEEPBLUE-262-264-6 - Accessibility Remediation

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/mlib-styles.css
app/views/hyrax/base/_form_files.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-268

DEEPBLUE-268 - Focus style is not perceivable

---

app/views/hyrax/admin/admin_sets/_show_document_list.html.erb
app/views/hyrax/collections/_show_document_list.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/_show_document_list.html.erb
app/views/hyrax/file_sets/_versions.html.erb
app/views/hyrax/my/collections/_modal_add_subcollection.html.erb
app/views/hyrax/my/collections/_modal_add_to_collection.html.erb
app/views/job_statuses/index.html.erb
config/locales/hyrax.en.yml

https://mlit.atlassian.net/browse/DEEPBLUE-270

DEEPBLUE-270 - Collection page accessibility remediation

---

app/assets/stylesheets/main.scss
app/views/hyrax/base/_form_files.html.erb
app/views/hyrax/base/_form_progress.html.erb
app/views/hyrax/base/_form_visibility_component.html.erb
app/views/hyrax/file_sets/_versioning.html.erb
app/views/records/edit_fields/_rights_license.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-269

DEEPBLUE-269 - File upload page accessibility remediation

---

Gemfile
app/helpers/deepblue/provenance_helper.rb
app/models/provenance.rb
app/services/deepblue/provenance_log_service.rb
config/application.rb
db/migrate/20230905155609_create_provenances.rb
db/schema.rb
spec/models/provenance_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-272

DEEPBLUE-272 - Convert Provenance Log to Database Storage

---

app/assets/javascripts/hyrax/save_work/save_work_control.es6

https://mlit.atlassian.net/browse/DEEPBLUE-274

DEEPBLUE-274 - DataSet edit javascript showing Other fields

---

app/controllers/hyrax/data_sets_controller.rb
app/jobs/ensure_doi_minted_job.rb
app/models/concerns/deepblue/doi_behavior.rb
app/services/deepblue/doi_minting_service.rb
spec/controllers/hyrax/data_sets_controller_spec.rb
spec/jobs/ensure_doi_minted_job_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-276

DEEPBLUE-276 - Ensure DOI throws error

---

app/helpers/deepblue/provenance_helper.rb
app/services/deepblue/provenance_log_service.rb

https://mlit.atlassian.net/browse/DEEPBLUE-272

DEEPBLUE-272 - Convert Provenance Log to Database Storage - 2

---

app/renderers/hyrax/renderers/creator_orcid_attribute_renderer.rb

https://mlit.atlassian.net/browse/DEEPBLUE-277

DEEPBLUE-277 - ORCID url should be https

---

app/helpers/deepblue/json_logger_helper.rb
app/services/deepblue/provenance_log_service.rb
spec/helpers/deepblue/provenance_helper_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-272

DEEPBLUE-272 - Convert Provenance Log to Database Storage - 3

---

app/helpers/deepblue/ticket_helper.rb

https://mlit.atlassian.net/browse/DEEPBLUE-260

DEEPBLUE-260 - Draft works are creating TDX tickets

---

app/assets/javascripts/hyrax/save_work/save_work_control.es6

https://mlit.atlassian.net/browse/DEEPBLUE-260

DEEPBLUE-274 - DataSet edit javascript showing Other fields - 2

---

app/views/hyrax/base/_items_no_action.html.erb
app/views/hyrax/base/_member_no_action.html.erb
config/application.rb
config/initializers/_orcid_service_integration.rb
spec/services/hyrax/orcid_service_integration_spec.rb

https://mlit.atlassian.net/browse/DEEPBLUE-280

DEEPBLUE-280 - Activate work edit file set delete

---

Gemfile
Gemfile.lock

https://mlit.atlassian.net/browse/DEEPBLUE-283

DEEPBLUE-283 - Add bagit gem

---

app/helpers/ahoy_helper.rb
app/services/ahoy/abstract_cleaner.rb
app/services/ahoy/dangling_event_cleaner.rb
app/services/ahoy/visits_cleaner.rb

https://mlit.atlassian.net/browse/DEEPBLUE-284

DEEPBLUE-284 - Clean up Ahoy event tables

---

app/models/aptrust_deposit.rb
app/models/concerns/filterable.rb
app/services/aptrust/aptrust_service.rb
config/aptrust.yml.sample

DEEPBLUE-285 - Send works to APTrust

---

app/services/aptrust/aptrust_service.rb

DEEPBLUE-285 - Send works to APTrust - 2

---

app/services/aptrust/aptrust_behavior.rb
app/services/aptrust/aptrust_info.rb
app/services/aptrust/aptrust_info_from_work.rb
app/services/aptrust/aptrust_service.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/aptrust/aptrust_uploader_status.rb

DEEPBLUE-285 - Send works to APTrust - 3

---

app/models/aptrust/status.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/aptrust/aptrust_uploader_status.rb

DEEPBLUE-285 - Send works to APTrust - 5

---

app/jobs/aptrust_upload_job.rb
app/jobs/aptrust_upload_work_job.rb
app/jobs/find_and_fix_old_job.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_config.rb
app/services/aptrust/aptrust_filter_work.rb
app/services/aptrust/aptrust_find_and_upload.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/aptrust/aptrust_uploader_status.rb
app/services/deepblue/abstract_find_curation_concern.rb
app/services/deepblue/find_and_fix_service.rb
app/services/deepblue/find_curation_concern_filter_date.rb
app/services/deepblue/find_curation_concern_filter_size.rb
spec/services/deepblue/find_curation_concern_filter_date_spec.rb

DEEPBLUE-285 - Send works to APTrust - 7

---

app/helpers/deepblue/metadata_helper.rb
app/jobs/aptrust_upload_job.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_filter_work.rb
app/services/aptrust/aptrust_find_and_upload.rb
app/services/aptrust/aptrust_info.rb
app/services/aptrust/aptrust_info_from_work.rb
app/services/aptrust/aptrust_service.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/deepblue/yaml_populate_service.rb
app/tasks/deepblue/yaml_populate.rb
lib/tasks/works_missing_edit_users.rake
spec/tasks/works_missing_edit_users_rake_spec.rb

DEEPBLUE-285 - Send works to APTrust - 8

---

app/controllers/aptrust/aptrust_statuses_controller.rb
app/presenters/aptrust/aptrust_statuses_presenter.rb
app/renderers/hyrax/renderers/creator_orcid_attribute_renderer.rb
app/services/ahoy/visits_cleaner.rb
app/services/aptrust/aptrust.rb
app/views/aptrust/_form.html.erb
app/views/aptrust/index.html.erb
config/routes.rb

https://mlit.atlassian.net/browse/DEEPBLUE-299

DEEPBLUE-299 - Display APTrust Statuses

---

app/controllers/aptrust/aptrust_statuses_controller.rb
app/helpers/deepblue/metadata_helper.rb
app/models/concerns/deepblue/file_set_behavior.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/deepblue/yaml_populate_service.rb
app/views/aptrust/index.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-301

DEEPBLUE-301 - Add export of versions to APTrust

---

app/jobs/aptrust_verify_work_job.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_config.rb
app/services/aptrust/aptrust_status_service.rb
app/services/aptrust/aptrust_uploader.rb

https://mlit.atlassian.net/browse/DEEPBLUE-302

DEEPBLUE-302 - Add APTrust upload validation

---

app/jobs/aptrust_verify_work_job.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_config.rb
app/services/aptrust/aptrust_status_service.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb

https://mlit.atlassian.net/browse/DEEPBLUE-302

DEEPBLUE-302 - Add APTrust upload validation - 2

---

app/controllers/aptrust/aptrust_events_controller.rb
app/jobs/aptrust_verify_job.rb
app/models/aptrust/status.rb
app/services/aptrust/aptrust.rb
app/services/aptrust/aptrust_config.rb
app/services/aptrust/aptrust_filter_work.rb
app/services/aptrust/aptrust_find_and_upload.rb
app/services/aptrust/aptrust_find_and_verify.rb
app/services/aptrust/aptrust_info.rb
app/services/aptrust/aptrust_info_from_work.rb
app/services/aptrust/aptrust_service.rb
app/services/aptrust/aptrust_status_service.rb
app/services/aptrust/aptrust_uploader.rb
app/services/aptrust/aptrust_uploader_for_work.rb
app/services/aptrust/aptrust_uploader_status.rb
app/services/aptrust/aptrust_verifier.rb
app/views/aptrust/events/index.html.erb
app/views/aptrust/index.html.erb

https://mlit.atlassian.net/browse/DEEPBLUE-309

DEEPBLUE-309 - Find and verify APTrust uploads job

---

bin/prepare-meta.working

correct perl script used to load items with cc licenses

corrected perl load script
