mlibrary/deepblue

app/presenters/hyrax/admin_set_options_presenter.rb
app/views/hyrax/base/_form_relationships.html.erb

This will allow us to have two types of admins:  one for DataSet, and one for any other type of work.

don't allow admin set for DataSet to be used by other work types.

---

config.ru
config/application.rb

copied from https://github.com/mlibrary/umrdr, especially
https://github.com/mlibrary/umrdr/blob/master/config.ru
I haven't verified that everything related to the relative URL root works (especially since there are no works deposited in that instance yet), but at least the front page loads.

support relative url root at /data

---

app/controllers/hyrax/data_sets_controller.rb

These methods (prepare_permissions, and reset_permissions) are used so that when viewing a tombstoned work, and the user is not admin, the user  will be able to see the metadata.  Since the work is restricted, it will ask the user to authenticate to view it, so by taking these actions before the show and after the show, we can allow the work show page to display.

make tombstone page accessible to everyone

---

app/helpers/deepblue_helper.rb
app/views/_ie_announcement.html.erb
app/views/_masthead.html.erb

Updated to handle edge and ie 10.
Have to use request.env['HTTP_USER_AGENT']. Ugh.
Code:
`module DeepblueHelper
def self.human_readable_size( value, precision: 3 )
ActiveSupport::NumberHelper::NumberToHumanSizeConverter.convert( value, precision: precision )
end
def user_agent()
user_agent =  request.env['HTTP_USER_AGENT']
user_agent
end
def users_browser()
user_agent = user_agent().downcase
@users_browser ||= begin
if user_agent.index('msie') && !user_agent.index('opera') && !user_agent.index('webtv')
'msie'
elsif user_agent.index('gecko/')
'gecko'
elsif user_agent.index('opera')
'opera'
elsif user_agent.index('konqueror')
'konqueror'
elsif user_agent.index('ipod')
'ipod'
elsif user_agent.index('ipad')
'ipad'
elsif user_agent.index('iphone')
'iphone'
elsif user_agent.index('chrome/') …

BLUEDOC-349-ie-error2

---

app/actors/hyrax/actors/file_actor.rb
app/actors/hyrax/actors/file_set_actor.rb
app/helpers/deepblue/ingest_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/characterize_job.rb
app/jobs/ingest_job.rb
app/models/job_io_wrapper.rb
config/initializers/hyrax.rb

* Changed the ingest-like jobs to use "ingest" queue.
* Added starting attach to work upload log and finished.
* Added (and passed around but did not use) a list of ids of the uploaded_files to ingest jobs

BLUEDOC-389 - Some files failing to upload in bulk upload 3

---

app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/uploads_controller.rb
app/jobs/attach_files_to_work_job.rb
app/models/concerns/deepblue/file_set_metadata.rb

* Added more logging, including tracking of the uploaded_file.id
* Added some more error trapping to attach files to work
* Changed the definition of file_size metadata from singular to multiple (was causing an exception that was being eaten until I added the above noted error trapping)

BLUEDOC-389 - Some files failing to upload in bulk upload 4

---

app/forms/deepbluedocs/default_work_form_behavior.rb
app/forms/deepbluedocs/dissertation_work_form_behavior.rb
app/forms/deepbluedocs/generic_work_form_behavior.rb
app/models/solr_document.rb

* References to ScholarsArchive have been removed.
* These references have been causing occasional errors to appear in the logs.

BLUEDOC-396 - ScholarsArchive references throws errors

---

app/actors/hyrax/actors/create_with_files_actor.rb
app/actors/hyrax/actors/file_actor.rb
app/helpers/deepblue/ingest_helper.rb
app/jobs/attach_files_to_work_job.rb
app/jobs/characterize_job.rb
app/jobs/create_derivatives_job.rb
app/models/job_io_wrapper.rb
lib/hydra/works/services/add_file_to_file_set.rb
lib/hydra/works/services/upload_file_to_file_set.rb
lib/tasks/new_content_service.rb

* The cause of this is that when a new version of a file is uploaded, the depositor overrides the actual uploading user.
* Added debug logging.
* AttachFilesToWorkJob was using: user = User.find_by_user_key( depositor ), which is incorrect when another user replaces a file version
* AttachFilesToWorkJob now looks up the current user
* Made sure current user is being passed into and along the ingest job chain

BLUEDOC-414 - File details page displays wrong user for file upload

---

app/services/hyrax/workflow/abstract_notification.rb

* Fix the generation of incorrect paths in notification messages.
Run the following from the console to fix /data/data/ in old notification messages:
selected = Mailboxer::Notification.all.select { |n| n.body =~ /\/data\/data\// }; selected.count
selected.each { |n| n.body = n.body.gsub( /\/data\/data\//, "/data/" ); n.save }; true

BLUEDOC-382 - Dashboard notification links to works not resolving

---

app/models/collection.rb
app/models/concerns/deepblue/metadata_behavior.rb
app/models/data_set.rb
app/models/file_set.rb
spec/models/concerns/deepblue/metadata_behavior_spec.rb

* Restricted list of metadata for collectins, file_sets, and works.
* Collections no longer include metadata for sub-collections or works.
* Works no longer include file_sets metadata.

BLUEDOC-426 - Work metadata file should only show public metadata

---

.solr_wrapper

* solr v6.6.5 is what we currently use in production

BLUEDOC-449 - Pin solr_wrapper to solr v6.6.5

---

app/views/_head_tag_extras.html.erb

* commented out reference to favicon.ico

BLUEDOC-515 - Favicon reference causes routing error

---

lib/append_content_service.rb
lib/build_content_service.rb
lib/tasks/new_content_from_yaml.rake
lib/tasks/new_content_from_yaml.rb
lib/update_content_service.rb

Add a version of the ingest scripts that will take multiple input files so that a single rake invocation can ingest multiple files and avoid the start-up overhead for invoking rake for each file

BLUEDOC-576 - Version of ingest script that takes multiple input files

---

app/models/concerns/deepblue/provenance_behavior.rb
app/models/concerns/deepblue/workflow_event_behavior.rb

Fixed case where embargo date is illegal during create causes error

BLUEDOC-547 - Embargo date and pick choice should display consistently 2

---

lib/tasks/new_content_service.rb

Also includes updates for description_file_set in new content service

BLUEDOC-724 - File set modify date not being set during backend ingest

---

.solr_wrapper.yml
config/solr_wrapper_test.yml

solr started failing to load. Set the solr version to 7.7.1

BLUEDOC-744 - Fix solr config

---

app/controllers/hyrax/file_sets_controller.rb

Fixes issue #548.  This update of the metadata will set a new Las-Modified date on the header of the file being downloaded, that will ensure that files with the same name are not downloaded from the cache.

when updating version of file, make sure the cache is refreshed.

---

app/assets/javascripts/hyrax/collections_utils.es6
app/assets/javascripts/hyrax/file_manager/sorting.es6
app/controllers/concerns/deepblue/works_controller_behavior.rb
app/controllers/hyrax/data_sets_controller.rb
app/controllers/hyrax/downloads_controller.rb
app/controllers/hyrax/file_sets_controller.rb
app/helpers/deepblue/interpolation_helper.rb
app/models/concerns/deepblue/email_behavior.rb
app/presenters/hyrax/collection_presenter.rb
app/services/deepblue/work_view_content_service.rb
config/application.rb

The expansions of default url not working for javascript.
Turns out that this function using a rest/json call. Restoring
json update/mutate ability.

BLUEDOC-858 - Re-order files function is not working

---

config/locales/hyrax.en.yml

The new website launch broke the link for the existing "M" logo. This commit adds the apps redirect for the previous link.
The Design System team is going to work on stable asset linking but for now, the redirect should be fine.

BLUEDOC-869 Add new link for logo

---

db/migrate/20200828174733_update_single_use_links.rb
db/schema.rb

BLUEDOC-906-add-columns-to-single-use-links-table (commit 2)

BLUEDOC-906 - Add columns to single_use_links table

---

Gemfile
Gemfile.lock
app/actors/hyrax/actors/after_optimistic_lock_validator.rb
app/actors/hyrax/actors/before_add_to_work_actor.rb
app/actors/hyrax/actors/before_model_actor.rb
app/actors/hyrax/actors/create_with_files_actor.rb
app/actors/hyrax/actors/environment.rb
app/actors/hyrax/actors/interpret_visibility_actor.rb
app/controllers/concerns/integrator/hyrax/works_behavior.rb
app/services/willow_sword/crosswalk_from_dc_data.rb
config/initializers/willow_sword.rb
config/routes.rb
db/migrate/20210622174656_add_api_key_to_users.rb
db/schema.rb

Here are some things to keep in mind:
1.  I made a change to the Gemfile.  After speaking to cottagelabs, they told me to use the develop branch of willow_sword ( this branch gives us the ability to change the kind of dc metadata processed by the gem), so this is one change to the Gemfile. The other is that in my dev environment I can't use the mysql gem, so I have commented this out.  @fritzfreiheit if you could, after merging this PR, do a fresh bundle install after uncommenting out that line.  This will obviously affect the Gemfile.lock file.  Then you can send a PR with the correct Gemfile and Gemfile.lock.
2.  I think there is a new migration that will have to be run in production for us to use token authentication.  The instructions for that are here: …

enable sword in deep blue data

---

app/actors/hyrax/actors/default_admin_set_actor.rb
app/controllers/concerns/integrator/hyrax/works_behavior.rb
config/initializers/willow_sword.rb

For sword release these are important notes to have in PR for future reference.
Things involved in this PR that might be forgotten.
1.  We are using the "develop" branch of the cottage lab sword implementation because it has a way to configure 
the dc data in config/initializers/willow_sword.rb.  We needed this because Deep Blue Data has some very specific
metadata that was not in the default out of the box configuration.
2.  When using the out of the box sword to ingest, the works where not being put in a workflow.  This was because
in this file app/actors/hyrax/actors/default_admin_set_actor.rb ( which before this PR was not subclassed ) if 
there is no admin set associated with the work, the work was put in the default admin set, which is configured
to have a one-step-deposit workflow. …

during sword put item in workflow and in collection requested.

---

app/actors/hyrax/actors/initialize_workflow_actor.rb
app/assets/javascripts/hyrax/save_work/save_work_control.es6
app/controllers/concerns/deepblue/works_controller_behavior.rb
app/services/deepblue/draft_admin_set_service.rb
app/services/deepblue/work_view_content_service.rb.backup
app/views/hyrax/base/_form_progress.html.erb
app/views/hyrax/dashboard/_draft_works.html.erb
app/views/hyrax/dashboard/show_admin.html.erb
app/views/hyrax/my/works/index.html.erb
config/locales/deepblue.en.yml
config/locales/hyrax.en.yml
config/workflows/draft_work_workflow.json
spec/controllers/concerns/deepblue/works_controller_behavior_spec.rb
spec/views/hyrax/my/works/index.html.erb_spec.rb

Here is an explanation of some of the technical changes.
So that only the "Submit for Review" button is managed by the js that checks that all required fields are filled in.
app/assets/javascripts/hyrax/save_work/save_work_control.es6
-    this.saveButton = this.element.find(':submit')
+    this.saveButton = this.element.find('#with_files_submit')
In this file
app/controllers/concerns/deepblue/works_controller_behavior.rb 
The methods create and update are defined, and this is where logic was added to take into account if the user during create is:
Creating a new work and requesting a review of the work OR
Creating a new work and just saving it as a draft
AND during update:
Updating a work in the mediated deposit workflow OR
Updating a draft work which is in the Draft works workflow
In …

adding Save as Draft functionality.

---

app/assets/javascripts/hyrax/save_work/save_work_control.es6
app/views/hyrax/base/_form_progress.html.erb

With this PR the "Save as Draft" and "Submit for Review" are enabled and disabled using the same criteria - basically that the required fields are filled in.
I want to point out  the difference between these two lines:
This grabs a specific id:
this.saveButton = this.element.find('#with_files_submit')
This grabs ALL submit buttons.
this.saveButton = this.element.find(':submit')
One thing that was challenging about this PR was that in the method preventSubmitIfAlreadyInProgress it was doing this:
this.saveButton.prop("disabled", true);
which did not send the submit buttons value on to the controller and so this line was returning nil always:
draft = params[:save_as_draft]
I changed the code in preventSubmitIfAlreadyInProgress to:
this.saveButton.prop("disabled", false); 
And the params …

make save as draft and submit for review button use the same javascript

---

config/workflows/draft_work_workflow.json

When you deactivate a work that has been saved as draft, it will not show up when you hit "Go" from the home page.  Only active works show up when searching.  
As reference, this is what the deactivate code does:
app/services/hyrax/workflow/deactivate_object.rb  (in the hyrax gem code):
module DeactivateObject
def self.call(target:, **)
target.state = Vocab::FedoraResourceStatus.inactive
end
end

deactivate work in draft mode.

---

app/controllers/hyrax/stats_controller.rb
app/presenters/hyrax/work_usage.rb
app/views/hyrax/stats/work.html.erb
config/routes.rb

In this PR I took care of my typo of using cvs when I should have been using csv.
I make the color of the text in the button white using the class `btn-primary`
When the csv file is output, it will contain the title of the work in the first line.  This is the code that does that:
```title = ["title => " + self.work.title.first]```
The output file name will follow this format:  workid_stats.csv.  You can see this being done in this code:
filename = params[:id] + "_stats.csv"
#This is an example that worked
#send_data @stats.to_csv, :type => 'text/csv; charset=utf-8; header=present', :disposition => 'attachment; 
filename=payments.csv'
target = "attachment`; filename=#{filename}"
send_data @stats.to_csv, :type => 'text/csv; charset=utf-8; header=present', :disposition => target
Also I put …

corrections to csv functionality

---

app/search_builders/hyrax/filter_suppressed.rb
app/search_builders/hyrax/my/works_search_builder.rb
app/search_builders/hyrax/works_search_builder.rb

In app/controllers/hyrax/my/works_controller.rb, you point to the search builder being used for the "My" tab:
def search_builder_class
Hyrax::My::WorksSearchBuilder
end
in app/search_builders/hyrax/my/works_search_builder.rb, you point to the filter method you need
self.default_processor_chain += [:remove_draft_works]
AND
In app/controllers/concerns/hyrax/works_controller_behavior.rb   (look at hyrax gem code, 
this file is monkey patched ), you point to the search builder being used for the "All" tab:
self.search_builder_class = WorkSearchBuilder
in app/search_builders/hyrax/works_search_builder.rb, you point to the filter method you need.
self.default_processor_chain += [:remove_draft_works]
In app/search_builders/hyrax/filter_suppressed.rb, you add the remove_draft_works method
def …

filter out works in draft admin set from the list of works and my works

---

app/actors/hyrax/actors/initialize_workflow_actor.rb
app/services/hyrax/workflow/draft_creation_notification.rb
config/workflows/draft_work_workflow.json

This file has changed: config/workflows/draft_work_workflow.json
So this has to be run:
bundle exec rake hyrax:workflow:load
I'm not sure if the "Draft works Admin Set" need to be edited and saved to have the changes in the workflow applied to it.  I did it on my local machine.

send notification when in draft and when transitioning to mediated workflow

---

app/jobs/sitemap_generator_job.rb
app/services/deepblue/sitemap_generator_service.rb
lib/tasks/create_sitemap.rake
public/robots.txt

https://tools.lib.umich.edu/jira/browse/BLUEDOC-1260
From my conversation on how fulcrum does their sitemap with Seth:
They use a gem.  Seth gave me these links to their code:
(1) the gem they use:  https://github.com/kjvarga/sitemap_generator
(2) how they set it up on the robots file:  https://www.fulcrum.org/robots.txt
(3) Their specific code change for the gem: https://github.com/mlibrary/heliotrope/blob/master/config/sitemap.rb
(4) link to their master sitemap file: https://www.fulcrum.org/sitemap.xml
(5) An example of one of their sitemap files.
https://www.fulcrum.org/sitemap2.xml
```<url>
<loc>https://www.fulcrum.org/concern/file_sets/5h73px66g</loc>
<lastmod>2019-10-02T01:07:08Z</lastmod>
<changefreq>monthly</changefreq>
<priority>0.5</priority>
</url>
(6) They build their sitemap …
```

generate sitemap code

---

app/models/concerns/deepblue/email_behavior.rb
app/models/concerns/deepblue/workflow_event_behavior.rb
config/locales/hyrax.en.yml

This addresses jira ticket:  https://tools.lib.umich.edu/jira/browse/BLUEDOC-568
Before this ticket, when a work was deleted, RDS received an email.  This tickets adds the following functionality:
Depository will also get an email, plus a  notification.
We talked about sending RDS a notification also, but decided against it because they don't use that very much, in addition the notification process in Hyrax is a bit complicated.  We could do something like this in email_behavior.rb in the method email_event_destroy_rds:
message = "This work has been deleted = " + EmailHelper.curation_concern_url( curation_concern: self )
admin_users = RoleMapper.map["admin"]
admin_users.each do |admin_email|
user = User.find_by_user_key admin_email
Hyrax::MessengerService.deliver(current_user, admin_user, …

send notification and email to depositor when work is deleted.

---

app/controllers/catalog_controller.rb
app/indexers/data_set_indexer.rb
app/indexers/hyrax/admin_set_indexer.rb
app/indexers/hyrax/collection_indexer.rb

When we go to testing and production, all collections, admin sets, and works will have to be re-index.
This is the JIRA ticket:
https://tools.lib.umich.edu/jira/browse/BLUEDOC-609

so that title sort can be done on works and collections.

---

app/controllers/hyrax/dashboard/collections_controller.rb

This fixes issue:
https://tools.lib.umich.edu/jira/browse/BLUEDOC-1024
When you upload a logo for the 1st time for a collection, the file ID is numeric.  When you go back to the branding page and you try to save it again, the file ID is no longer numeric, but a path.  The code was checking that the path contained "public," but for some reason, it did not contain "public," so I changed the code to check that it contained a string.
General rule:
New logo file ids will contain a numeric value.
Existing logo file ids will contain a path.
Not quite sure why "public" was not in the path.  In hyrax it works with this check.  When this goes to testing, need to check that the logo and banner show up for the collection page.  There may be some file configuration to the path that may need tweaking.

check logo id is string not just public.

---

app/helpers/analytics_helper.rb
app/services/deepblue/analytics_integration_service.rb
config/initializers/analytics_integration.rb
spec/services/deepblue/analytics_integration_service_spec.rb

This is for issue:  https://tools.lib.umich.edu/jira/browse/BLUEDOC-1290
In looking at this, it seems like a good and simple solution is to filter out the events for which there are more than 50 Events with the same visit_id.  The visit_id is a key to the Ahoy::Visit table.  From speaking to Fritz, he is under the impression that the visits_ids are reset after 4 hours.  From looking that the table, it looks like there is a one-to-one correspondence between the visit_id and ip, so for now, we may be able to get away from having to count the actual ip visits, but rely on the visit_id as an indicator of ips that keep making the same request.
Since the Ahoy gem, according to the documentation, takes care of known crawlers, for now we will not check ips to see if they are crawlers.  With the …

more filtering on stats

---

app/views/hyrax/base/_attribute_rows.html.erb

When there are more than 5 authors, in the work page, list them in paragraph form, do not implement more/less for now.  Because there are "<a" tags associated with the author list, the more/less that we have does not work.  For now, after talking to Rachel, we decided to wait on this.  
For reference, in the description, which uses more/less there is a function that changes the "tags" to text, and if you do this the more/less works, but then you loose the link.  Here is a snippet of that code:
<%= raw ("<span class=\"more\">" + iconify_auto_link(description) + "</span>") %>
The iconify_auto_link is what converts the tags to text.

remove more/less from author list.

---

app/helpers/analytics_helper.rb
app/jobs/reset_condensed_events_job.rb

This is a very straight forward Job.  Here are some things to keep in mind:
(1)  by_request_only: true  ==> This means the Job will not run on schedule but when the user hits "Run" on the Manage Jobs page.
(2)  subscription_service_id: reset_condensed_events_job  ==>  this will enable users to subscribe to the job, and by doing so receive an email when the job completes.
(3) job_msg_queue << "Start processing at #{DateTime.now}"   ==> This is the text of the message that gets emailed.
(4)  email_results  ==> This is the line that sends out the email.

make a job to reset condensed table

---

app/services/hyrax/default_middleware_stack.rb
spec/actors/hyrax/actors/data_set_actor_spec.rb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-52
I brought this file over from hyrax 3 because it was missing the last actor:
middleware.use Hyrax::Actors::InitializeWorkflowActor
Strangely, this was in the 2.9 version.  Not sure what happened.  I suspect this is a bug in Hyrax 3.
Without this actor, he work would be created, but it would not be put in the workflow, so you did not see the blue "Pending review" badge, and when you opened the "Review Approval" area, the options with the radio buttons were missing. 
As a reminder, the actors are in the dir: app/actors/hyrax/actors
Remember that the actors have the CRUD methods in them.

put work in workflow

---

app/search_builders/hyrax/collection_search_builder.rb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-56
This functionality was dropped during the merge to Hyrax 3.

allow sorting of All collections in dashboard.

---

app/controllers/hyrax/dashboard/collections_controller.rb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-65
This was a fix that I worked for Hyrax, it did not make it in v3, but it is important.

logo record processing checks for string, not just public dir

---

app/services/hyrax/multiple_membership_checker.rb

Fixes this issue:  https://mlit.atlassian.net/browse/DEEPBLUE-69
The issue here was that when a user tried to add a work to a collection or create a work into an existing collection, the system would generate an error like this:
Collections Error: You have specified more than one of the same single-membership collection type (type: User Collection, collections: User collection and User collection Two)
This was because it was checking if the collection type allowed works to belong to more than one collection.  
I have moved this service over from the hyrax v3 area, to basically change this line of code:
```Hyrax::FindObjectsViaSolrService.find_for_model_by_field_pairs(model: ::Collection, field_pairs: field_pairs, use_valkyrie: false)```
In the original file, use_valkyrie was being passed …

allow works to be added to collections.

---

app/actors/hyrax/actors/default_admin_set_actor.rb

This is to address this issue:  https://mlit.atlassian.net/browse/DEEPBLUE-70
This PR will allow sword deposits to be place in the correct admin set, and in turn be put in the workflow.
Here are something to remember when debugging this issue on my local machine:
(1) Go to this dir:  /Users/blancoj/work/sword_work
(2) In order not to bother with the Kye set this to false:
config/initializers/willow_sword.rb
config.authorize_request = false
(3)  You can then issue this command from the dir I indicated in (1)
curl --request POST --url http://localhost:3000/data/sword/collections/cj82k729x/works \
--header 'Content-Disposition: attachment; filename=metadata.xml' \
--header 'Content-Type: application/xml' \
--header 'In-Progress: false' \
--header 'Packaging: application/atom+xml;type=entry' …

allow work to be placed in correct admin set when using sword.

---

app/indexers/data_set_indexer.rb
app/models/data_set.rb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-81
Two things to keep in mind from this PR:
(1) With version 3 of Hyrax, this was brought in:
solr_doc[:tombstone_tesim] = object.tombstone
But prior to this version, we used:
solr_doc[:tombstone_ssim] = object.tombstone
So I reverted back to using tombstone_ssim.
(2) This old PR: https://github.com/mlibrary/deepblue/pull/1016  made a change to the entomb! method to do this:
self.state = Vocab::FedoraResourceStatus.inactive
What this does is change the Status of the work from Published to Under review, so if you Filter for it on the dashboard you will find it in the Under review status, when the work was actually published.  In order to find the works that are tombstoned, you sort on the dashboard as Visibility > Restricted and Status > …

allow works to be tombstoned in version 3 of hyrax.

---

app/models/concerns/umrdr/umrdr_work_metadata.rb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-86
This was a good PR to look at showing a metadata added to the system:
https://github.com/mlibrary/deepblue/pull/102/files
Solr may need to be reindexed.  I had an item that had did had this metadata field, and after I made this change, the metadata was not showing in the work page, but after I saved it again, it showed up.

add citation to related materials to show in work page.

---

app/views/hyrax/dashboard/collections/show.html.erb

Fixes https://mlit.atlassian.net/browse/DEEPBLUE-106
The collection page was not being displayed because one line of code was inconsistent with new version.

display collection page without error.

---

app/views/hyrax/base/_show_work_body.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-108
In the show page of a work, don't show the Relationship unless the user is admin.

only show relationship on show page to admins

---

app/presenters/hyrax/ds_file_set_presenter.rb
app/presenters/hyrax/work_show_presenter.rb
app/views/hyrax/file_sets/_actions.html.erb
spec/presenters/hyrax/ds_file_set_presenter_spec.rb

This fixes: https://mlit.atlassian.net/browse/DEEPBLUE-117
This will need further testing on testing.  The idea is to allow depositors to be able to delete their work and the files attached to that work while the work is in draft mode.

allow works in draft mode to be deleted and files by depositor.

---

app/views/hyrax/homepage/_featured_works.html.erb

Fixes:  https://mlit.atlassian.net/browse/DEEPBLUE-157
This is an overwrite with this line being the one that changed:
<h3 class="sr-only"><%= t('hyrax.homepage.featured_works.title') %></h3>

remove unnecessary h2, make h3

---

app/views/hyrax/base/_form_create_anonymous_links.html.erb

Fixes: https://mlit.atlassian.net/browse/DEEPBLUE-154
if too file size is too large, don't display the button to create anonymous link

don't allow creation of anonymous link if size too big
